### ISSUE TITLE
Questions and comments on forecasting base classes and refactoring

### ISSUE THREAD

**Issue by Lovkush-A** [alan-turing-institute/sktime#1020]
I am trying to understand as much as possible before doing any actual refactoring.  Here are several comments/questions/suggestions. High chance I am mistaken or missing the point - if so, just say so!

1.  _base.py. the docstrings that an end-user will see are the docstrings in the BaseForecaster. E.g. for `fit`, they will see docstring containing `The base forecaster specifies the methods and method signatures that all forecasters have to implement.`
2. _base.py. `update_predict`
    1. What *is* `update_predict`? My guess is that it would be shorthand for `update` and then `predict` (similar to `fit_transform`). But this does not seem to be what is going on. Maybe it needs to be renamed.
    2. I think `cv` needs to be renamed. `cv` stands for cross validation, but I do not think there is any cross validation happening here.
    3. You raise a `NotImplementedError` if `return_pred_int`. I do not think we should have `NotImplementedError` in functions that will not be overwritten in children classes. In my head there are two options: have NotImplementedError in appropriate place in the children or simply not have `return_pred_int` as a parameter
    4. Currently, `update_predict` does input checks and then calls` _predict_moving_cutoff`. This is confusing; it does not look like any updating happens. Furthermore, it is different convention to other functions: `fit` calls `_fit`, `predict` calls `_predict`. Note that my confusion here is related to point 2.i about not knowing what update_predict is intended to do.
3. `score`. minor points only:
    1. change 'MAPE' to 'sMAPE' in first line of docstring
    2. maybe rename 'score' to 'sMAPE_score' or 'sMAPE'??
    3. where is this `score` method used?
4. `_get_y_pred` and `_get_pred_int`.
    1. using the name `get` makes it sound like the method is a getter method (as in setters and getters), but I don't think these are getter methods. I suggest renaming these
    2. the functions are hard to read. need to add some whitespace at least
    3. `_get_pred_int` is used in only place (according to my vscode search), namely _tbats. seems unusual that a helper function defined in base is used in only one place, but maybe there is intentions to use it more.
5. `_set_fh`. The very first if condition and error message seems incorrect to me. We have `if not requires_fh` in if condition and the error message says 'fh must be passed'. Presumably the rest of the if loops need to be checked; I have not checked them.

**Comment by fkiraly** [comment]
I am trying to understand as much as possible before doing any actual refactoring.  Here are several comments/questions/suggestions. High chance I am mistaken or missing the point - if so, just say so!

>1.  _base.py. the docstrings that an end-user will see are the docstrings in the BaseForecaster. E.g. for `fit`, they will see docstring containing `The base forecaster specifies the methods and method signatures that all forecasters have to implement.

Yes, indeed - this may pose some problems, so we may have to carefully think about what the docstrings say.
Perhaps something user facing, usage related. The docstring as of now should go in the extension template (it's probably already there, too).

2. _base.py. `update_predict`
    1. What *is* `update_predict`? My guess is that it would be shorthand for `update` and then `predict` (similar to `fit_transform`). But this does not seem to be what is going on. Maybe it needs to be renamed.

Correct, completely agree with you that this is too confusing right now, hence #982.
The user expects it's `update` then `predict`, based on `fit_predict` etc. This expectation is clearly frustrated.
FYI, it may have been me who originally designed it that way, but it's still true 😄 

 >   2. I think `cv` needs to be renamed. `cv` stands for cross validation, but I do not think there is any cross validation happening here.

Yes, also one for #982. See my suggestion `cutoffs`.

>    3. You raise a `NotImplementedError` if `return_pred_int`. I do not think we should have `NotImplementedError` in functions that will not be overwritten in children classes. In my head there are two options: have NotImplementedError in appropriate place in the children or simply not have `return_pred_int` as a parameter

I'm also unhappy with how prediction intervals are "bolted on", I think I do agree with you.
See #984. Probably you're secretly reading my thoughts (or issues).

>    4. Currently, `update_predict` does input checks and then calls` _predict_moving_cutoff`. This is confusing; it does not look like any updating happens. Furthermore, it is different convention to other functions: `fit` calls `_fit`, `predict` calls `_predict`. Note that my confusion here is related to point 2.i about not knowing what update_predict is intended to do.

Yes - would be very happy on suggestions on how we can straighten this out without being too invasive in the re-work/re-factor.

>3. `score`. minor points only:
>1. change 'MAPE' to 'sMAPE' in first line of docstring

? where?

>2. maybe rename 'score' to 'sMAPE_score' or 'sMAPE'??

Not a good idea, since it's an *estimator* level unified interface point, selecting one default `score` appropriate for the scitype.
 
>    3. where is this `score` method used?

Typically called by `GridSearchCV` and derivates.

>4. `_get_y_pred` and `_get_pred_int`.
    1. using the name `get` makes it sound like the method is a getter method (as in setters and getters), but I don't think these are getter methods. I suggest renaming these

Agreed, but not much harm done by the strange name since private methods that neither user nor extender will typically see?

>2. the functions are hard to read. need to add some whitespace at least

Where precisely? Docstrings?

>3. `_get_pred_int` is used in only place (according to my vscode search), namely _tbats. seems unusual that a helper function defined in base is used in only one place, but maybe there is intentions to use it more.

I was wondering where it was used and why it was there, but I did only major surgeries, which is moving it over from `_SktimeForecaster`. This might be one of the minor surgeries to do later on. PR appreciated, but it should make sure that nothing downstream breaks.

> 5. `_set_fh`. The very first if condition and error message seems incorrect to me. We have `if not requires_fh` in if condition and the error message says 'fh must be passed'. Presumably the rest of the if loops need to be checked; I have not checked them.

that looks correct, because it is in the loop `if self._is_fitted`, which means we are already in `predict` and no `fh` has been seen so far, not in `fit` and not in `predict` - and this is the latest point at which it must be passed if it hasn't been so far.

**Comment by fkiraly** [comment]
PS:
>High chance I am mistaken or missing the point 

Very low chance, I'd say.
Because there's the implication that I would be too 😄

**Comment by fkiraly** [comment]
>Is it possible for users to change the score method? If not, then I think users shoud be allowed to choose.

No, and this is a default from scikit-learn. You can choose your `score` if you tune, but there must be a sensible default (according to that design principle). The `score` interface point represents this sensible default, rather than a point of choice.

>The harm is in losing time of future contributors and slowing down their comprehension of the code

Well, feel free to propose a change. But I think there are much more important things to refactor, i.e., the user facing interface points which we also discussed above - #982, #984.

>The functions _get_pred_int and _get_y_pred have no whitespace in the actual code of the function (so everything except the docstring)

Oh dear, it hurts looking at this. You are right...

>I am happy to do a PR, but I do not know what the PR would consist of.

How about #982 and #984 instead (see above), this is quite concrete (but has to be checked with @mloning, @aiwalter), or, even more importantly, the forecasting refactor?

**Comment by mloning** [comment]
Thanks @Lovkush-A for the feedback! 

I don't think `score` is used much at the moment, we implemented it because scikit-learn has it, but none of us were ever really convinced of it as a main interface point I believe.

**Comment by fkiraly** [comment]
I think this has been addressed in the various pieces of refactor, @Lovkush-A?
