### ISSUE TITLE
Common terminology and glossary

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#109]
Could we agree on some common terminology so that we use the same variable names for the same things? Probably also a good idea to create a glossary in our wiki to keep track of them.  

How do we refer to:

**(the number of) different kinds of measurements (i.e. columns in the dataframe)?**
`n_columns` or `n_features` or `n_dimensions`?

I'd prefer `n_columns` since is the least ambiguous and intuitive given our data container, and also in line with the names of compositors like `ColumnTransformer` and so on.

**(the number of) rows in the dataframe?**
`n_rows`, `n_samples` or `n_instances`?

I'd prefer either `n_rows` (same reasons as above) or `n_samples` (in line with sklearn).

**the number of time points in series?**
`n_obs`?

**Comment by fkiraly** [comment]
Great idea! Or we keep confusing each other in our meetings.
My opinion:

"samples" has problems since it can mean different things in different communities. Stat/ML people will think of *independent* samples, whereas signal processing or data mining people might think of the number of time points. Also, within stats/ML, it can mean at a same time a *single* data point (row), or a *collection* of data points (many rows), compare "data set contains 100 samples" and "5 training samples".

I would hence go with `n_rows`, `n_columns` (for data frame), and `n_obs` (for time series).

In terms of terminology, perhaps "instance", "column/feature/variable", and "time point" are clearest?

**Comment by TonyBagnall** [comment]
yes this is a good idea, although I don't think we will settle on mutually acceptable terminology easily :) So I prefer instance or case instead of row. I don't like referring to the dimensions of a multidimensional problem as columns, as that is dependent on our particular data representation. I just don't think of data in tables, I think of a case as an encapsulated object. I'm not sure about the time series of each dimension, we have always called it the length of the series.  Or we could just used $n$ for number of cases, $m$ for series length and $d$ for dimensions as we do in papers :)

**Comment by jasonlines** [comment]
I agree with Tony that this is both a good idea and may also not be easy :) 

**Rows/instances/cases/samples**

My vote would be **cases** too - I also don't naturally think of data as being in a table and wouldn't want to be semantically tied to that; I think of the thing in question of being an atomic unit in its own right that doesn't need to reside in a set of data (a 1 row table is a bit of a hack imo!). We also frequently extract cases from a dataframe to put them in, for example, a list for better processing where there are no rows. Also, for equivilancy between other machine learning packages on a semantic level, many implementations have no notions of tables, rows, columns, etc (e.g. Weka) so it would be better to keep it more conceptual in my opinion


**Dimensionality**

I again would agree with Tony (surprise surprise!) and vote for **dimensions** as that is transferable between different tools and interpretations when talking about multi-dimensional data BUT with the caveat that I've only ever used or cared about multidimensional data previously in the situation where all channels/columns/dimensions are time series. In sktime, perhaps columns is more general here for our implementation as we may want to store more complex data in the same container along with the time series, e.g. scaler columns for age, or name, and so on. With that in mind I'm not sold either way

**Series length**

I personally think **length** is fine here and am a bit weary of observation as the terminology. For example, if we want to pad data or interpolate to make unequal length -> equal length, then some of the values are not _observations_ in a sense. In those cases (in my mind at least) the series would be of the same length but not necessarily contain the same number of observations. Maybe I'm getting a bit philosophical there though :)

**Comment by mloning** [comment]
* single letters may make it hard to remember and less readable for someone unfamiliar with the code,
* yes, columns may also contain primitives, so it's not always different dimensions in time, and "dimensions" may be easily confused with dimensions of an array (e.g. the output of `X.shape`),
* so maybe `len_series` rather than `n_obs`? I think I'd prefer to have something with an `n` to make the relation clear to the other dimensions of the data container (rows, columns, time) but can't think of anything else for now ... or `n_time_points`?
* given that our toolbox is tightly coupled to the data representation, maybe it makes sense to names things in our code with reference to it and avoid conceptual ambiguities across domains/fields?

**Comment by TonyBagnall** [comment]
but also length gets confusing if we start to consider unequally spaced, timestamped series. Is it the length of the time window or, err, the number of observations? tricky stuff

**Comment by TonyBagnall** [comment]
so I will hold out for

**Comment by mloning** [comment]
Okay, I think I'm also happy with
* `n_instances` 
* `n_columns`

I'm less sure about 
* `n_obs` or `len_series` or `n_timepoints`? I share the concern about timestamped series where length refers to something else. So I think I'd prefer `n_timepoints`. Any other thoughts on this one?

**Comment by TonyBagnall** [comment]
Also on naming conventions, personally I dont like appending Classifier to each classifier, it is redundant imo. So I would have ColumnEnsembler rather than ColumnEnsembleClassifier. It extends Classifier. I wouldnt call RandomForest RandomForestClassifier or an SVM and SVMClassifier. However, I can contradict myself somewhat, some we do call that if they are just pipelines,  e.g. ShapeletTransformClassifier is a shapelet transform + a classifier

**Comment by TonyBagnall** [comment]
but on reflection, none of the classifiers we are talking about can handle unequally spaced time series. I'm leaning towards series_length or len_series

**Comment by TonyBagnall** [comment]
and do we always prefer e.g. n_classes to num_classes? I tend to use the latter, but that might just be me

**Comment by mloning** [comment]
* I'd stick with `n_*` instead of `num_*` 
* how would you distinguish classifiers from regressors with the same name?

**Comment by TonyBagnall** [comment]
well most of our lot are num_ not n_ so its whether I refactor or not :) Why the preference? Cos its shorter? maybe we can live with both for now. 
>how would you distinguish classifiers from regressors with the same name?
such as? Some classifiers can be adapted to do regression, but that would be enhancing the capabilities of the classifier. In  regressors package I'd expect to see specific regression algorithms such as GLIM, GaussianProcesses etc. Its very hard to be consistent with MyThngClassifier. for example, what would you call CART? CARTClassifier? Classification and Regression Tree Classifier? :)

**Comment by TonyBagnall** [comment]
oh and for n_ and num_, in some classes we have used both! :) I'll refactor for n_instances, n_columns, series_length for now

**Comment by mloning** [comment]
I've added a glossary here: https://github.com/alan-turing-institute/sktime/wiki/Glossary

**Comment by mloning** [comment]
I think I've come to prefer `n_timepoints` over `series_length` because (i) it makes it clear that it's another dimension of the data table (all start with `n_`) and  (ii) it avoids confusion when taking about timestamped data

**Comment by mloning** [comment]
Moved to [glossary](https://github.com/alan-turing-institute/sktime/wiki/Glossary)
