### ISSUE TITLE
inconsistency in the sktime installation guides 

### ISSUE THREAD

**Issue by tensorflow-as-tf** [alan-turing-institute/sktime#1203]
On the sktime.org website, the "Development versions" installation guide section of the "Installation" page (https://www.sktime.org/en/latest/installation.html#mac-osx) suggests different steps of installation from the "Git and GitHub workflow" section of the "How to contribute" page (https://www.sktime.org/en/latest/contributing.html#id10).

If a new developer installs sktime following the Development version installation steps, they would have to incorporate the steps of the "Git and GitHub workflow" to be able to contribute.

It is a question whether it is necessary to have "Development versions" installation steps and separate installation steps in the "Git and GitHub workflow" section. 

If the answer is no, a possible solution would be to direct the reader to the "Git and GitHub workflow" from the "Development versions" installation using a link.

If the answer is yes, it would be advisable to make it clearer for a new contributor which installation steps they should follow.

**Comment by fkiraly** [comment]
I see - good points!

The thing is, the steps to install a dev version are in a sense "simpler" than setting oneself up for contribution.

So, there are indeed two workflows:

* just installing the dev version
* setting oneself up for contribution, which includes installing an editable dev version

And I see how the two are inconsistent, since it's not clear for instance that you have to follow a slightly different sequence of git commands, but *still* ensure that you satisfy the build requirements.

Reworking the developer guide is high up on our priority list for docs - contributions in the area are also much appreciated. Let us know if you are up for that. We'll have a doc sprint w/c Aug 23.

**Comment by mloning** [comment]
There's an additional workflow: building a release version from source when no pre-built wheel is available for your operating system.

**Comment by fkiraly** [comment]
I think this is addressed in #1707.
