### ISSUE TITLE
Create user documentation

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#13]
1. Use sphinx with doc strings
2. Settle on convention how to write doc strings
3. Disseminate info of how to write doc strings that conforms to it

**Comment by mloning** [comment]
Added support for binder #180

**Comment by big-o** [comment]
Quote from #200:

> > Documentation
> 
> Agreed with what you say, could be more beginner friendly - though even if Sphinx, someone needs to invest time to make it...
> for now we thought getting feature complete on the TSC/TSR and forecasting fronts would be a priority, as to showcase the reduction/composition arc-hitecture, but certainly documentation is something to revisit.

I completely understand - especially in the early days of the project it can be more important to get some functionality working so that you have something to document in the first place! I just wanted to raise the point on docs because I've been in the position where I wished I'd prioritised documentation earlier. Once you have quite a bit of undocumented functionality it quickly becomes a large task to fix. But if you start early and improve the documentation incrementally with each update, it can be much more manageable and easy to maintain.

**Comment by fkiraly** [comment]
Maybe we could run another dev & doc sprint sometime early next year?

**Comment by mloning** [comment]
Closed, discussion moved to #128
