### ISSUE TITLE
[ENH] Forecasting: prediction interval add-on wrapper

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1363]
We should have a wrapper that adds prediction intervals to forecasters that have none.

These can be obtained in a generic way by running sliding forecasts on historic data.

A prediction interval for the k-step ahead prediction can then be obtained from variance or quantiles of actual errors of historical k-step ahead predictions.

As stated above, this should be a wrapper such as `AddPredInt` which allows to invoke forecasters like

`AddPredInt(FancyForecaster(params), interval_type="quantile")`

**Comment by fkiraly** [comment]
related to #984, perhaps worth doing that first

**Comment by bethrice44** [comment]
Are there still plans to add generic prediction intervals for those that don't have them? I'm looking for a way to do this and came across [this library](https://mapie.readthedocs.io/en/latest/index.html). There is a [PR in progress](https://github.com/scikit-learn-contrib/MAPIE/pull/135) to add a class specifically for time series. 

Currently, due to the ordering of `X` and `y` in the fit method and the fact it works only with arrays not pandas series/ dataframes the method doesn't work, but I think it could be adapted to be compatible with `sktime`.

**Comment by fkiraly** [comment]
Yes, @bethrice44, there is already `NaiveVariance` which you can use for that purpose.

The forecasting variant of the MAPIE library you linked is in this pull request:
https://github.com/alan-turing-institute/sktime/pull/2542

and will be available in 0.12.0 later this month if another core developer will review it by then...

**Comment by fkiraly** [comment]
This should be closed, since it was implemented in https://github.com/alan-turing-institute/sktime/pull/1865
