### ISSUE TITLE
[ENH] AutoEnsembleForeacaster should have a method to use inverse error as weights

### ISSUE THREAD

**Issue by aiwalter** [alan-turing-institute/sktime#1404]
**Describe the solution you'd like**
`AutoEnsembleForeacaster` should be able to automatically calculate internally the error of the forecasters and use the inverse error as weights. Credits to @RNKuhns who came up with this idea :)

There should be a `method="inverse-error"` added.

**Comment by AngelPone** [comment]
@aiwalter are you working on this? If not, I can help. While I suggest  to add this `inverse-error` method into `EnsembleForecaster` instead of `AutoEnsembleForecaster`, such as `EnsembleForecaster(forecasters, weights='inverse-error')`.  If added into `AutoEnsembleForecaster`, `method` and `regressor` may be confused.

**Comment by aiwalter** [comment]
Hi @AngelPone we missed you :) especially for the HTS topic, but glad that you are back again :) I would put it into `AutoEnsembleForecaster`, we might have more such weight selection algos implemented there. Then we would have the regressor method and the inverse-error one. The `EnsembleForecaster` is for me more a vehicle for users to give custom weights.

**Comment by AngelPone** [comment]
@aiwalter agree. I will work on this.
