### ISSUE TITLE
[MNT] reduce redundancy in package dependency configurations

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1482]
We currently have multiple places in which package dependencies are specified and need to be updated:

* `setup.py`
* `.appveyor.yml`
* `build_tools/requirements.txt`
* `build_tools/hard_dependencies.txt`
* `.binder/prelim_requirements.txt`
* `.binder/requirements.txt`

surely there must be a better way to replicate one and the same set of package requirements?

Related: #1281, notebook tests using same requirements as binder.

**Comment by fkiraly** [comment]
FYI, @aiwalter, @freddyaboulton, @mloning

**Comment by lmmentel** [comment]
Would it be interesting to try [pyproject.toml](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/) to consolidate the dependency specification and then (possibly) generate `requirements.txt` in the context it might be needed?

Alternatively `requirements.txt` are composable so it's possible to create a base set of requirements and include those in more env specific situations. I don't know your build pipeline that well yet but I'll have a closer look.

**Comment by lmmentel** [comment]
It seems that a suggestion for trying out `pyproject.toml` was also mentioned in #1150

**Comment by fkiraly** [comment]
Thanks for investigating this, @lmmentel!

**Comment by lmmentel** [comment]
I've spent some time looking at the CI/CD pipelines and I I think it might be a little too complex for what it does.

Here is what I learned:

#### github actions

- [.github/workflows/assign-contributor.yml](.github/workflows/assign-contributor.yml)
- [.github/workflows/build-and-test.yml](.github/workflows/build-and-test.yml)
    - ``code-quality`` linting, style, format
    - ``test-examples`` run all the example notebooks
    - ``build`` build wheels for ``macos-10.15`` and python 3.6, 3.7, 3.8, 3.9 and run test on the wheels
- [.github/workflows/upload-to-pypi.yml](.github/workflows/upload-to-pypi.yml)
    - ``deploy`` build wheels for ``macos-10.15`` and python 3.6, 3.7, 3.8, 3.9, run test on the wheels and publish to PyPI

#### azure pipelines

- [build_tools/azure/build_manylinux_wheels.yml](build_tools/azure/build_manylinux_wheels.yml) build linux wheels 
- [build_tools/azure/publish.yml](build_tools/azure/publish.yml) upload wheels to azure 

#### appveyor

- [build_tools/appveyor/run_with_env.cmd](build_tools/appveyor/run_with_env.cmd) build wheels for win?

What I would like to propose is to simplify the pipelines 

- try to run all on github actions since it support the [main os hosts](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners)
- use [cibuildwheel](https://github.com/pypa/cibuildwheel) to build wheels across the matrix of ``win``, ``linux``, ``mac`` and python 3.6, 3.7, 3.8, 3.9
- publish to PyPI

I'll be working on a draft in #1620 

If there any reason o information that I'm missing  that it would not work?

**Comment by fkiraly** [comment]
FYI @mloning, @freddyaboulton.

@lmmentel, this sounds excellent!
We wanted to move to GitHub actions eventually.

FYI, @mloning had already started here
https://github.com/alan-turing-institute/sktime/pull/1321
but hasn't finished this, I think it's on hold - don't know the reason, perhaps simply lack of time.
@mloning, do you want to comment what happened?

**Comment by lmmentel** [comment]
Thanks for bringing up #1321 @fkiraly. I went through it and it seems we're moving in a similar direction. Would be great to connect with @mloning to align on how to push it over the finish line.

I already have a working [pyproject.toml](https://github.com/lmmentel/sktime/blob/enh-add-pyproject-toml-issue-1482/pyproject.toml) that could be the single source of truth for dependencies and project metadata. I also refactored the CI steps to reflect how and what dependencies are installed for particular steps.

@fkiraly would it be possible to enable CI runs on #1620 so we test run the refactored workflows?

How about we continue the discussion over at #1620 so that we can follow the design decisions?
