### ISSUE TITLE
[BUG] AutoARIMA fit breaks with sktime 0.8.0, sklearn 1.0, pmdarima 1.8.2

### ISSUE THREAD

**Issue by asksteph** [alan-turing-institute/sktime#1503]
**Describe the bug**

**To Reproduce**

```python
import numpy as np
import pandas as pd
import statsmodels.api as sm
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.forecasting.arima import AutoARIMA

df = sm.datasets.macrodata.load_pandas()['data']
df['q_date'] = df.apply(lambda x: str(int(x['year'])) + '-Q' + str(int(x['quarter'])), axis=1)
df['date'] = pd.PeriodIndex(df['q_date'], freq='Q').to_timestamp()
df = df.set_index('date').to_period("Q")

y = df['realgdp']
y_train, y_test = temporal_train_test_split(y, test_size=30)
forecaster = AutoARIMA(sp=4)
forecaster.fit(y_train)
```

Error:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_22920/2308042316.py in <module>
     13 y_train, y_test = temporal_train_test_split(y, test_size=30)
     14 forecaster = AutoARIMA(sp=4)
---> 15 forecaster.fit(y_train)

~\AppData\Roaming\Python\Python38\site-packages\sktime\forecasting\base\_base.py in fit(self, y, X, fh)
    178         #####################################################
    179 
--> 180         self._fit(y=y_inner, X=X_inner, fh=fh)
    181 
    182         # this should happen last

~\AppData\Roaming\Python\Python38\site-packages\sktime\forecasting\base\adapters\_pmdarima.py in _fit(self, y, X, fh, **fit_params)
     47         """
     48         self._forecaster = self._instantiate_model()
---> 49         self._forecaster.fit(y, X=X, **fit_params)
     50         return self
     51 

~\anaconda3\envs\skt080\lib\site-packages\pmdarima\arima\auto.py in fit(self, y, X, **fit_args)
    175         # Temporary shim until we remove `exogenous` support completely
    176         X, fit_kwargs = pm_compat.get_X(X, **fit_args)
--> 177         self.model_ = auto_arima(
    178             y,
    179             X=X,

~\anaconda3\envs\skt080\lib\site-packages\pmdarima\arima\auto.py in auto_arima(y, X, start_p, d, start_q, max_p, max_d, max_q, start_P, D, start_Q, max_P, max_D, max_Q, max_order, m, seasonal, stationary, information_criterion, alpha, test, seasonal_test, stepwise, n_jobs, start_params, trend, method, maxiter, offset_test_args, seasonal_test_args, suppress_warnings, error_action, trace, random, random_state, n_fits, return_valid_fits, out_of_sample_size, scoring, scoring_args, with_intercept, sarimax_kwargs, **fit_args)
    715         )
    716 
--> 717     sorted_res = search.solve()
    718     return _return_wrapper(sorted_res, return_valid_fits, start, trace)
    719 

~\anaconda3\envs\skt080\lib\site-packages\pmdarima\arima\_auto_solvers.py in solve(self)
    284 
    285         # fit a baseline p, d, q model
--> 286         self._do_fit((p, d, q), (P, D, Q, m))
    287 
    288         # null model with possible constant

~\anaconda3\envs\skt080\lib\site-packages\pmdarima\arima\_auto_solvers.py in _do_fit(self, order, seasonal_order, constant)
    231             self.k += 1
    232 
--> 233             fit, fit_time, new_ic = self._fit_arima(
    234                 order=order,
    235                 seasonal_order=seasonal_order,

~\anaconda3\envs\skt080\lib\site-packages\pmdarima\arima\_auto_solvers.py in _fit_candidate_model(y, X, order, seasonal_order, start_params, trend, method, maxiter, fit_params, suppress_warnings, trace, error_action, out_of_sample_size, scoring, scoring_args, with_intercept, information_criterion, **kwargs)
    528         # check the roots of the new model, and set IC to inf if the
    529         # roots are near non-invertible
--> 530         ic = _root_test(fit, ic, trace)
    531 
    532     # log the model fit

~\anaconda3\envs\skt080\lib\site-packages\pmdarima\arima\_auto_solvers.py in _root_test(model, ic, trace)
     36 
     37     if p + P > 0:
---> 38         max_invroot = max(0, *np.abs(1 / model.arroots()))
     39     if q + Q > 0 and np.isfinite(ic):
     40         max_invroot = max(0, *np.abs(1 / model.maroots()))

~\anaconda3\envs\skt080\lib\site-packages\sklearn\utils\metaestimators.py in __get__(self, obj, owner)
    107             # delegate only on instances, not the classes.
    108             # this is to allow access to the docstrings.
--> 109             if not self.check(obj):
    110                 raise attr_err
    111 

~\anaconda3\envs\skt080\lib\site-packages\sklearn\utils\metaestimators.py in _check(self, obj)
    195             return False
    196         # raise original AttributeError
--> 197         return getattr(delegate, self.attribute_name) or True
    198 
    199 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Expected behavior**

This code works in version 0.7.0 and would return the fitted ARIMA model.

**Additional context**

**Versions**
<details>

System:
    python: 3.8.11 (default, Aug  6 2021, 09:57:55) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\szipk\anaconda3\envs\skt080\python.exe
   machine: Windows-10-10.0.19042-SP0

Python dependencies:
          pip: 21.0.1
   setuptools: 58.0.4
      sklearn: 1.0
       sktime: 0.8.0
  statsmodels: 0.13.0
        numpy: 1.19.5
        scipy: 1.5.4
       Cython: 0.29.14
       pandas: 1.3.3
   matplotlib: 3.4.3
       joblib: 1.1.0
        numba: 0.54.1
     pmdarima: 1.8.2
      tsfresh: 0.18.0
</details>

**Comment by asksteph** [comment]
Downgrading to statsmodels 0.12.1 didn't fix the error for me. @fkiraly Would you post the versions of all the sktime-related libraries?

**Comment by fkiraly** [comment]
@asksteph, but this would mean it's actually a problem of `pmdarima`, since that's where the error is coming from?
(not `statsmodels` as I originally thought)

Would it be possible for you to try isolate the problem to `pmdarima.arima` (using `sklearn` 1.0) and if that's where it's from, post on the `pmdarima` GitHub and link the issue here?

**Comment by aaronreidsmith** [comment]
👋🏻 

As a contributor from the `pmdarima` side, hopefully I can speak to the issue. We were utilizing `scikit-learn`'s [`if_delegate_has_method`](https://scikit-learn.org/stable/modules/generated/sklearn.utils.metaestimators.if_delegate_has_method.html). That function has since been [deprecated](https://github.com/scikit-learn/scikit-learn/issues/20506) in favor of [`available_if`](https://scikit-learn.org/stable/modules/generated/sklearn.utils.metaestimators.available_if.html?highlight=available_if#sklearn.utils.metaestimators.available_if). We had a [fix](https://github.com/alkaline-ml/pmdarima/pull/455) in place fairly quickly after `scikit-learn`'s 1.0 release that will use `if_delegate_has_method` on older versions of `scikit-learn` and `if_available` on newer versions. This fix is included in `pmdarima` [1.8.3](https://github.com/alkaline-ml/pmdarima/releases/tag/v1.8.3), but it does mean that `pmdarima` 1.8.2 and `scikit-learn` 1.0 are unfortunately incompatible.

**Comment by fkiraly** [comment]
Hello @aaronreidsmith! Thanks to you and @asksteph for tracking down the problem!

Based on this, I assume that a new, vanilla installation of `sktime` wouldn't suffer from this bug, since it would install the newest releases respectively?

Further, @aaronreidsmith, I would be interested to hear your opinion on devensive version bounds, see #1480. Is that a good thing, e.g., have upper bounds on everything and only increase them after testing new upper bounds? Or does it cause a lot of trouble if multiple packages in the dependency tree do this?

**Comment by fkiraly** [comment]
Problem no longer exists on sktime 0.12.X and most up-to/date installation.

**Comment by fkiraly** [comment]
@asksteph, kindly let us know if this has disappeared for you too, or not.
