### ISSUE TITLE
Hive-Cote implementation

### ISSUE THREAD

**Issue by frankl1** [alan-turing-institute/sktime#158]
Hi,

Can you provide an example of how to implement HIVE-COTE using sktime ?

Thanks

**Comment by TonyBagnall** [comment]
hi, so the final way of building hive-cote is still in development, because we want to release it with a contract time. tbh we never build it as one classifier. It is much better to build each component and post process the final classifier. I'm just debugging components to make sure the output is not significantly different to the java version, tsml. Working document is here, which I will update this week.

**Comment by frankl1** [comment]
Thank you very much,

Looking forward for the release.

**Comment by fkiraly** [comment]
Hm, but isn't there already the option to build it in a modular way already? 
It just might not be optimized.

This example has RISE
https://github.com/alan-turing-institute/sktime/blob/master/examples/univariate_time_series_classification.ipynb
and surely HIVE-COTE is just a matter of putting the right building blocks together in the right sequence?

**Comment by fkiraly** [comment]
(re-opening because I'm also interested in the answer to the question, in the variation I've just posted)

**Comment by fkiraly** [comment]
@TonyBagnall : post-processing = compilation, i.m.o. - very interested in this topic, it might be worth discussing in a separate thread as it seems like a major feature to me

**Comment by TonyBagnall** [comment]
its a bit more complex than putting them in a pipeline, since you need a weight estimate of the accuracy from the training data, and there are bespoke ways of doing that, and a voting scheme. However, this is very simple and we have it in place, just need to test and push it.

**Comment by fkiraly** [comment]
if I may attempt to translate: this means in-principle you could build it as a pipeline, but in terms of components we are currently missing one, namely the ensembler/compositor that is used in HIVE-COTE?

**Comment by TonyBagnall** [comment]
yes you could, although I tend to think of it hierarchically rather than linearly, in that HIVE-COTE sits on top of the others. Top level also needs to handle the time contract, determining method of accuracy estimation, and threading each component if configured thus. Jason has a version and when he comes up for air from teaching this week he will I hope sort it out I'm currently running some experiments related to this issue in tsml (java version), and will aim to port over best practice to sktime. Happy to discuss tomorrow

**Comment by fkiraly** [comment]
alright, maybe let's ask then the easier variant of the question: can we build all the components classifiers of HIVE-COTE, considered as top-level ensemble, that is, HIVE-COTE minus the top layer? We have RISE (above).
Yes, let's chat tmrw.
