### ISSUE TITLE
[ENH] design and API specification: contract time

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#159]
update 2021-08-19: some algorithms now have a contract time feature, but I fear that interfaces may become inconsistent over time.
We need a proper specification for contractable algorithms, i.e., what attributes and/or methods should they implement.

Original issue:

---

Arising from some algorithms from UEA/TSC, and discussion in #158: some these have a nice feature of "contract time", i.e., one can specifiy a (maximum) time for them to run.

This is a brilliant idea as something to have - next to, of course, an algorithm providing estimates of its own runtime.

I'm wondering: should this kind of control, e.g., runtime, compute & contracts, be a dedicated interface point across all methods? That, for example, compositors and pipelines can use if they want, similar to the nested hyper-parameter interface?

**Comment by TonyBagnall** [comment]
so we are making each component "Contractable" in java interface speak, meaning you have the option to fix the time. Ultimately, we have two ways of fulfilling a contract: the classifier estimates how long it will take itself and (adaptively) configures itself appropriately (relevant to RISE and interval length esp), but then a higher level controller is able to impose an algorithmic constraint (e.g.  stop with fewer trees if the contract is fulfilled).

**Comment by TonyBagnall** [comment]
so I imagine the final hive-cote will
1) look for precomputed results, if present use them
2) if not put each component in its own thread,
3) allow the component to either estimate accuracy in its own way (e.g. bagging) or wrap in a cross validator
4) determine the contract to give each component
so then you can just build HiveCote with a fixed time and it will do the best it can. The research issue is then, how to balance all these factors intelligently. We use a simplified reinforcement learning approach at the moment, but plenty to do

**Comment by techtide** [comment]
Is HIVE-COTE implementation ready for use yet?

**Comment by TonyBagnall** [comment]
hi, I believe it is on the hive-cote branch, @jasonlines will know

**Comment by MJimitater** [comment]
Thanks for this great repo! Has HIVE-COTE already been implemented/merged to master branch?

**Comment by MJimitater** [comment]
All good, I saw the imlementation [here](https://github.com/alan-turing-institute/sktime/blob/db86ed7a0c63599e26deb86d0bc03422e1bb8f8e/sktime/classification/hybrid/_hivecote_v1.py) 👍

**Comment by fkiraly** [comment]
@MatthewMiddlehurst, @TonyBagnall, I think we need to design and write up a proper contract time interface - perhaps in the form of a mixin that specifies interfaces. There also should be generic unit tests for contractable estimators.

**Comment by fkiraly** [comment]
do you want to make a start for this, @MatthewMiddlehurst?

**Comment by MatthewMiddlehurst** [comment]
Currently working on getting HC2 in the package (#842), as I have told a number of people we would try to get a working version this summer.

Happy to take a look after, however.

**Comment by TonyBagnall** [comment]
yes we need HC2 equivalence first, but a simple interface for contractable classifiers makes sense.

**Comment by TonyBagnall** [comment]
we now have hc2 equivalence. We discussed this at classifier dev meeting on 20/10/21. We are not sure it merits an interface/mixin. 
"We need a proper specification for contractable algorithms, i.e., what attributes and/or methods should they implement."

The Contractable interface would be a placeholder, since the contract is set as a single variable (time in minutes) in the constructor and there are no methods associated with it. It might contain a couple of variables and nothing else. 

Now benefit would be for testing instance of in unit testing, but I don't think this capability should be unit tested, at least not in the standard unit testing. We are trying to get each test under 20 secs. Contracting is meant for long runs, at least an hour, and is not meant to be exact. I am not sure how to usefully unit test it.  TTo do it sensibly will add 10+ minutes to the test time for little benefit. Happy to hearr your thoughts @fkiraly , but I think we should close this issue.

**Comment by TonyBagnall** [comment]
after discussion at a TSC developer meeting, we decided to not implement this as an interface at this time and to stick with the current tag system
