### ISSUE TITLE
[ENH] window summaries and lagged reducer

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1612]
Design rom the Sep 16 design meeting.

FYI @danbartl, @ltsaprounis (have agreed to take this one).

We actually already had this lying around, it would supersede #1581 and address #1577.

---
design proposal for components implementing (implicit) requirements from David's proposal:

```python
feature_extractor = LaggedWindowSummarizer(
  window_functions = {
    "mean":   (None, [1,8], [7,14]), #(None, [(1,7), (1, 14), (8, 7), (8,14)])
    "median": (None, [1,2,3,4], [2,]),
    "std":    (None, [1], [2,5]),
    "kurt":   (None, [1], [5]), # strings same as in pandas?
    custom_function (Series -> float): (sthsth), #maybe later
    custom_transformer: (sthsthelse), # maybe later
     },
)
# "mean" : {lags : [1, 8], window_lengths : [7, 14]}
# "mean" : [(1,7), (1, 14), (8, 7), (8,14)] - FK prefers this
# same as
# "mean" : generate_windows(lags = [1, 8], window_lengths = [7, 14])

# -> Leonidas to adapt Daniel's code

calendar_features = CalendarDummies(
  base_frequency = "month",
  calendar_dummies = ['month','quarter','year',],
  calendar_other = ['proportion_total'],
)

# series-to-series
#  -> Daniel working on CalendarDummies 1356
#  -> fourier features to add, series-to-series

forecaster = LaggedReducer(
    regressor = RandomForestRegressor(), 
    transformers = [
        feature_extractor,
        calendar_features
        ]
)

# -> satya tentatively, or first person finished with rest
```

`LaggedReducer`

implements *direct forecasting approach on the lagged features*

What happens in `fit(y, fh= [1, 5, 7], X)`

1. create `X_for_regressor` matrix with columns:

* mean_aggr_1, mean_aggr_2, ..., median_aggr_1, etc = summaries applied to `y`
* calendar_feat_1, calendar_feat_2, ... = calendar transformer applied to `y`
* anything from `X` (if applicable), no transforms are applied to `X`

and `y_for_regressor` with columns:

* `lag_1`, `lag_5`, `lag_7` (in future) = lagged versions of `y`

2. we fit random forest to predict `lag_1` from `X_for_regressor`, `lag_5` from `X_for_regressor`, etc

What happens in `predict`

1. create lagged features for the "to predict line"

2. use fitted random forest to predict `lag_1` etc based on this

recursive: would have to apply transformation to the forecasts - sounds inefficient

FK opinion: let's implement only "direct" first

References: 
* [M5 winning solution](https://github.com/Mcompetitions/M5-methods/tree/master/Code%20of%20Winning%20Methods/A1/3.%20code/2.%20train
* [M5 post-opp analysis (from the organisers)](https://www.researchgate.net/publication/344487258_The_M5_Accuracy_competition_Results_findings_and_conclusions)

**Comment by fkiraly** [comment]
from discussion in the regular meeting: the above design does not allow lags in `y` and `X`, as discussed in #1577.

So we need to extend `LaggedReducer`, replace it by

```python
forecaster = LaggedReducer(
    regressor = RandomForestRegressor(), 
    transformers_X = [
        feature_extractor,
        calendar_features
        ],
    transformers_y = [
        feature_extractor,
    ]
)
```

**Comment by fkiraly** [comment]
I just noticed sth: if `X` is by default used, then `transformers_X` is not needed - we can just use the `ForecastingPipeline`.
I.e., we could have lags in `X` via sth like

```python
forecaster = ForecastingPipeline(steps=[
        ("X_lags", my_lagged_window_summarizer),
        ("lagged_reducer", LaggedReducer(
            regressor = RandomForestRegressor(),
            transformers = [
                feature_extractor,
                calendar_features,
                ],
        )
   ]
)
```

**Comment by Dwarak-PCI** [comment]
@fkiraly I suppose you plan to implement direct strategy instead of recursive since it is inefficient. Is there any way to provide window_length (lags) in the ForecastingPipeline?

I can use my_lagged_window_summarizer to get statistics of lagged variables, but what if I want to use lagged variables itself as exogenous variable.

**Comment by fkiraly** [comment]
> I can use my_lagged_window_summarizer to get statistics of lagged variables, but what if I want to use lagged variables itself as exogenous variable.

you would define

```python
my_lagged_summarizer = LaggedWindowSummarizer(
  window_functions = {
    etc
     },
)
```

This would ensure that the lagged variables are used in the `LaggedReducer` as exogeneous variables.
The `ForecastingPipeline` applies transformations in `steps` to the exogeneous variables `X`, so once it reaches the `LaggedReducer`, the exogeneous data contains the lagged variables.

**Comment by fkiraly** [comment]
@Dwarak-PCI, for your other questions:

> @fkiraly I suppose you plan to implement direct strategy instead of recursive since it is inefficient.

Yes/no - we first focus on direct, but ultimately we also want to implement recursive since it's a common strategy. It is probably not great, but it's the user who should choose in the end...

> Is there any way to provide `window_length` (lags) in the `ForecastingPipeline`?

Partially answered above - the pipeline has no lags, you have to provide it in the transformer component which does the lagging, see examples above.

**Comment by ltsaprounis** [comment]
> @fkiraly I suppose you plan to implement direct strategy instead of recursive since it is inefficient. 

@Dwarak-PCI - Since we already store the training sets of X & y as  forcaster._X and forecaster._y after fit, it will be easy to implement this in the predict method for the recursive strategy. Yes, predict will take longer, but it's feasible.

**Comment by Dwarak-PCI** [comment]
Thank you very much for the clarification @fkiraly , @ltsaprounis ! Appreciate your time and hard work on this :)

**Comment by danbartl** [comment]
Hi with the implementation of all the "preparation" pull requests finished we now can discuss the final structure for "the lagged reducer". 

You can find the prototype here:
https://github.com/danbartl/sktime/blob/global_forecasting_rebased/global_fc_example.py


Instead the original design of:
```
forecaster = LaggedReducer(
            regressor = RandomForestRegressor(),
            transformers = [
                feature_extractor,
                calendar_features,
                ],
        )
```

I chose to go for:
```
kwargs = {
    "lag_config": {
        "lag": ["lag", [[1, 0]]],
        "mean": ["mean", [[3, 0], [12, 2]]],
        "std": ["std", [[4, 0]]],
    }
}

forecaster = make_reduction(
    regressor,
    scitype="tabular-regressor",
    transformers=[WindowSummarizer(**kwargs)],
    window_length=None,
)
```

Main idea is to provide an optional argument transformers that would be applied to y - in our case, WindowSummarizer. To make why consider this example:

We have a dataframe with two exogeneous variables
<html>
<body>
<google-sheets-html-origin>

timepoint | y | X1 | X2
-- | -- | -- | --
1 | 0.5 | 1 | 2
2 | 0.4 | 0.8 | 1.6
3 | 0.3 | 0.6 | 1.2
4 | 0.3 | 0.6 | 1.2
5 | 0.25 | 0.5 | 1
6 | 0.1 | 0.2 | 0.4


</body>
</html>

When we use make reduction with a window length of 3 we would get:

<html>
<body>
<google-sheets-html-origin>

  |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | Window Length | 3 |   |   |   |   |   |   |   |  
make_reduction |   | y_lag1 | y_lag2 | y_lag3 | X1_lag1 | X1_lag2 | X1_lag3 | X2_lag1 | X2_lag2 | X2_lag3
  | y_4 | 0.3 | 0.4 | 0.5 | 1 | 0.8 | 0.6 | 2 | 1.6 | 1.2
  | y_5 | 0.4 | 0.3 | 0.3 | 0.8 | 0.6 | 0.6 | 1.6 | 1.2 | 1.2


</body>
</html>

While this works nicely with a small amount of data and a short window length, it is easy to see how that becomes a very huge array when we have many instances, a large amount of exogeneous information, and high frequency data.

E.g., the M5 competition featured 42.840  time series of daily data for 5 years. Participants often calculated features across the entire past year (365 timepoints) and used multiple exogeneous features (holiday encoding, snap days etc.) So if we assume 20 exogenous features we get an array of size:

(5-1)*365*20*365*42840 = 456,588,720,000 

Actually, however, people would often use only something like 30 lagged features of y that are calculated across the 365 past observations, e.g. rolling means, standard deviations etc. Also X values would only rarely be lagged, and not by much (maybe one period), which gives:

(5-1)*365*30*42840 + (5-1)*365*21*42840 = 3,189,866,400

So a fraction of the problem. 

Another issue is that the functions that were typically applied (rolling mean, std, kurtosis) have native rolling implementations in pandas and are quite fast in a pandas data frame when combined with groupby operations across the 42.840 instances. make_reduction, however, will currently generate an array that does not allow for an application of those native pandas rolling window functions.

Therefore, the prototype currently has the following functionality:

- pass a transformer argument that is applied to y with then reduction function, both in the transform and the predict step
- infer the window length from the transformer argument (see open points below for an explanation)
- X is not lagged at all. Instead use 

```
ForecastingPipeline(WindowSummarizer(...))`
```

to lag any variables of X that you feel the need to.

Open points:
- What to do with window length in this case? Window length is redundant, since it is implied by WindowSummarizer (e.g. for the kwargs argument above, we have a window length of 14 (maximum of shift and lag for mean = [12,2]). Currently WindowSummarizer contains an fit argument self.truncate_start that captures this. (so will be 12 in this example). We could rename self.truncate_start  to self.window_length and check that if a transformer is provided that contains its own self.window_length argument, we would use that.



The key code snippet is presented here:

```
   if isinstance(y.index, pd.MultiIndex):
        # danbartl: not yet operates across all transformers
        tf_fit = transformers[0].fit(y)
        X_from_y = tf_fit.transform(y)

        X_from_y_cut = X_from_y.groupby(level=0).tail(
            n_timepoints - tf_fit.truncate_start
        )
        # X_from_y = LaggedWindowSummarizer(**model_kwargs,X)
        # fix maxlag to take lag into account
        X_cut = X.groupby(level=0).tail(n_timepoints - tf_fit.truncate_start)

        yt = y.groupby(level=0).tail(n_timepoints - tf_fit.truncate_start)
        Xt = pd.concat([X_from_y_cut, X_cut], axis=1)
    else:
        z = _concat_y_X(y, X)
        n_timepoints, n_variables = z.shape

        fh = _check_fh(fh)
        fh_max = fh[-1]

        if window_length + fh_max >= n_timepoints:
            raise ValueError(
                "The `window_length` and `fh` are incompatible with the length of `y`"
            )

        # Get the effective window length accounting for the forecasting horizon.
        effective_window_length = window_length + fh_max
        Zt = np.zeros(
            (
                n_timepoints + effective_window_length,
                n_variables,
                effective_window_length + 1,
            )
        )

        # Transform data.
        for k in range(effective_window_length + 1):
            i = effective_window_length - k
            j = n_timepoints + effective_window_length - k
            Zt[i:j, :, k] = z

        # Truncate data, selecting only full windows, discarding incomplete ones.
        Zt = Zt[effective_window_length:-effective_window_length]

        # Return transformed feature and target variables separately. This
        # excludes contemporaneous values of the exogenous variables. Including them
        # would lead to unequal-length data, with more time points for
        # exogenous series than the target series, which is currently not supported.
        yt = Zt[:, 0, window_length + fh]
        Xt = Zt[:, :, :window_length]

```

**Comment by fkiraly** [comment]
thanks!

Could you kindly give an example of, how, given this design, how one would write down the following:
* including lagged `y` by lags 1,2,3 as exogeneous variables in the reduction
* including lagged window summaries of `y` by lags 1, 2 and window size 5 as exogeneous variables
* including lagged `X`, by lags 1, 2, 3, as exogeneous variables
* * including lagged window summaries of `X` by lags 12, 24 and window size 12 as exogeneous variables

**Comment by danbartl** [comment]
```
#Example 1
from sktime.forecasting.compose import ForecastingPipeline
from sktime.forecasting.base import ForecastingHorizon

kwargs = {
    "lag_config": {
        "lag": ["lag", [[1, 0], [2, 0], [3, 0]]],
    }
}

regressor = make_pipeline(
    RandomForestRegressor(),
)

forecaster = make_reduction(
    regressor,
    scitype="tabular-regressor",
    transformers=[WindowSummarizer(**kwargs)],
    window_length=None,
)

#Example 3 - None for transformers does not work yet, but easy to adjust
#  - no window needed since number of lag of y in this example

regressor = make_pipeline(
    RandomForestRegressor(),
)

forecaster = make_reduction(
    regressor,
    scitype="tabular-regressor",
    transformers=None,
    window_length=None,
)

pipe = ForecastingPipeline(
    steps=[
        ("a", WindowSummarizer(n_jobs=1, target_cols=["event_type_1", "snap"],
                                **kwargs)),
        ("forecaster", forecaster),
    ]
)


#Example 4 - I also included lags of y to make example more interesting

kwargs_y = {
    "lag_config": {
        "lag": ["lag", [[1, 0], [2, 0], [3, 0]]],
    }
}

kwargs_x = {
    "lag_config": {
        "mean": ["mean", [[12, 12 ], [24, 12 ]]],
    }
}


regressor = make_pipeline(
    RandomForestRegressor(),
)

forecaster = make_reduction(
    regressor,
    scitype="tabular-regressor",
    transformers=[WindowSummarizer(**kwargs_y)],
    window_length=None,
)

pipe = ForecastingPipeline(
    steps=[
        ("a", WindowSummarizer(n_jobs=1, target_cols=["event_type_1", "snap"],
                             **kwargs_x)),
        ("forecaster", forecaster),
    ]
)

```

Example 2 I do not understand, why window size 5 when I only need lags for periods 1 and 2?

**Comment by fkiraly** [comment]
> Example 2 I do not understand, why window size 5 when I only need lags for periods 1 and 2?

For the regression prediction of the next time point (at fh 1), I want to use:
* the summary of y over the window covering times 0, -1, -2, -3, -4; 
* the summary of y over the window covering times -1, -2, -3, -4, -5

**Comment by fkiraly** [comment]
Also, I thought about this as an example which uses all four features, not four different examples. Sorry, should have been more clear.

**Comment by fkiraly** [comment]
Further, can you kindly explain `"lag": ["lag", [[1, 0], [2, 0], [3, 0]]],`?
This seems awfully nested, for just wanting lags at 1, 2, 3 periods...

**Comment by fkiraly** [comment]
Other question: lag config for `x` and `y` seem inconsistent.
Should it be *11* (not 12) in the `kwargs_x`, or should it be *1* (not 0) in the `kwargs_y`?

**Comment by danbartl** [comment]
> For the regression prediction of the next time point (at fh 1), I want to use:
> 
> the summary of y over the window covering times 0, -1, -2, -3, -4;
> the summary of y over the window covering times -1, -2, -3, -4, -5

Ok but then you need to tell which function should be applied across that window, in this example the function mean:
```
kwargs = {
    "lag_config": {
        "mean": ["mean", [[5, 0], [5, 1] ]],
    }
}
```

under the assumption that we are currently at t = 1, this would give
mean_5,0 the mean of the past 5 observations: 0, -1, -2, -3, -4;
mean_5,1 the mean of the past 5 observations lagged by one observation: -1, -2, -3, -4, -5

> Further, can you kindly explain "lag": ["lag", [[1, 0], [2, 0], [3, 0]]],?
> This seems awfully nested, for just wanting lags at 1, 2, 3 periods...

We have four things we need to consider:

- the name of the newly generated column (especially useful for custom functions to be applied)
- the name of the function to be applied (or custom function definition)
- the window across which functions is applied
- the shift of that window

All of those are covered with the current syntax. Now for lag we might agree to use a special kind of logic since we actually only need two of those arguments and lag is of course frequently used.

```
def count_gt100(x):
    """Count how many observations lie above threshold 100."""
    return np.sum((x > 100)[::-1])

kwargs = {
    "lag_config": {
        "lag": [0,1,2],
        "mean": ["mean", [[4, 0], [14, 0] ]],
        "cgt100": [count_gt100, [[3, 2]]],
    }
}
```

One further simplification would be possible - we could drop the name argument, or make it optional.
Name of Custom function definition  would then be resolved to column name, e.g.

I really think this would be a better design (lag specification is counter intuitive, see also section below)

```
kwargs=
{
    "lag_config": {
        "lag": [0,1,2],
        "mean": [[4, 0], [14, 0]],
        count_gt100: [[3, 2]],
    }
}
```

would give a pd.DataFrame with names
```
lag_0, lag_1, lag_2, mean_4_0, mean_14_0 and count_gt100_3_2
```
and optionally allow user to specify
```
kwargs=
{
    "lag_config": {
        "lag": [0,1,2],
        "mean": [[4, 0], [14, 0]],
        count_gt100: [[3, 2]],
    },
    "lag_config_names": ["lag","mean","counting"]
}
```
which would resolve to
```
lag_0, lag_1, lag_2, mean_4_0, mean_14_0 and couning_3_2
```

> Other question: lag config for x and y seem inconsistent.
> Should it be 11 (not 12) in the kwargs_x, or should it be 1 (not 0) in the kwargs_y?

You are right I misspecified the example 
Lag 1,2,3 would currently be specified like this
(window_length for lags is 1, shift is either 0, 1, 2.)

```
kwargs = {
    "lag_config": {
        "lag": ["lag", [[1, 0], [1, 1], [1, 2] ]],
    }
}
```

I agree that this is counter intuitive, so we really should implement the special logic for lags argument, see above, to only have the starting at argument and not window length. 

```
kwargs = {
    "lag_config": {
        "lag": [0,1,2],
    }
}
```

Btw I changed the shift logic for the shift specification at the suggestion of @ngupta23, because of his convincing argument here:

> "mean": ["mean", [7, 8]]
>  Does this mean that the window length = 7 starting at lag = 8? So if each - or x represents a point in the time series, then 
> does this take the mean of the points marked in x?
```
- - - - - - - - - - - - x x x x x x x - - - - - - -
```
> If my understanding is correct, should this not be lag=7 instead of lag=8 since the last point would be lag=0?
> Thanks.


While that logic make sense for window functions (mean of past 7 observations is specified as: shift starting at 0, window length 7), a consistent application is a bit confusing for lags (shift starting at 0, window length 1) for first lag, (shift starting at 1, window length 1)  for second lag. 

So we could also drop the consistency here and instead have a special logic for lags, so we would not provide [0,1,2] but [1,2,3] for lags:

```
kwargs=
{
    "lag_config": {
        "lag": [1,2,3],
        "mean": [[4, 0], [14, 0]],
        count_gt100: [[3, 2]],
    }
}
```

**Comment by danbartl** [comment]
So favored example after changes discussed

```
kwargs_y = {
    "lag_config": {
        "lag": [1,2,3],
    }
}

kwargs_x = {
    "lag_config": {
        "mean": [[12, 12 ], [24, 12 ]],
    }
}


regressor = make_pipeline(
    RandomForestRegressor(),
)

forecaster = make_reduction(
    regressor,
    scitype="tabular-regressor",
    transformers=[WindowSummarizer(**kwargs_y)],
    window_length=None,
)

pipe = ForecastingPipeline(
    steps=[
        ("a", WindowSummarizer(n_jobs=1, target_cols=["event_type_1", "snap"],
                             **kwargs_x)),
        ("forecaster", forecaster),
    ]
)
```

**Comment by fkiraly** [comment]
Ok, I´m increasingly confused now. How is the current syntax for `kwargs_x` and `kwargs_y` consistent? If a lag of 1 gets the number 0, a lag of 2 gets the number 1, should a lag of 12 not get a number 11? To be consistent.
(not saying anything about opinions yet, just want to understand the current encoding)

**Comment by danbartl** [comment]
From the docstring
```
        For example for `window = [4, 3]`, we have a `window_length` of 4 and
        `starting_at` of 3 to target the four days prior to the last three days.
        Here is a representation of the selected window:
        |-------------------------------|
        | x * * * * * * * x x x z - - - |
        |-------------------------------|
        ``-`` = future observations.
        ``z`` = current observation, to which the window should be relative to.
        ``x`` = past observations.
        ``*`` = selected window of past observations across which summarizer
                function will be applied.
```

So lag [1,0] has a window length of 1 (thats what a lag is) and starting_at 0 (starting with the current observation, span a window of one in the past.

```

        |-------------------------------|
        | x x x x * z - - - |
        |-------------------------------|
        ``-`` = future observations.
        ``z`` = current observation, to which the window should be relative to.
        ``x`` = past observations.
        ``*`` = selected window of past observations across which summarizer
                function will be applied.
```

Lag [1,1] has a window length of 1 (thats what a lag is) and starting_at 1 observation in the past - so target the second observation.

```

        |-------------------------------|
        | x x x * x z - - - |
        |-------------------------------|
        ``-`` = future observations.
        ``z`` = current observation, to which the window should be relative to.
        ``x`` = past observations.
        ``*`` = selected window of past observations across which summarizer
                function will be applied.
```

Mean [12,12] means go back 12 observations in the past, and then take the previous 12 observations and apply the mean across them


```

        |-------------------------------|
        | x * * * * * * * * *  * * * x x x x x x x x x x x x z - - - |
        |-------------------------------|
        ``-`` = future observations.
        ``z`` = current observation, to which the window should be relative to.
        ``x`` = past observations.
        ``*`` = selected window of past observations across which summarizer
                function will be applied.
```

**Comment by fkiraly** [comment]
still, the window specification seems inconsistent to me.

Let´s be mathematically precise.
Let's denote by ` y[t]` the observation at integer time `t`, and `t=0` is the present/current.
Then, what window does the pair `[a, b]` in your conceptual model refer to?

The window between `y[-a]` and `y[-a-b+1]`, inclusive? (formally, collection of observations `y[i]` with `-a-b < i <= a`)
Or, the window between `y[-a-1]` and `y[-a-b]`, inclusive? (formally, collection of observations `y[i]` with `-a-b <= i < a`)
(both of these give you windows with `b` observations in them, at integer indices)
Sth else?

To me it seems, the convention is different for the "lags" case, and the "12 in the past" case, hence inconsistent.

**Comment by danbartl** [comment]
the docstring mentions that  [a,b]  refers to window_length and starting_at parameters. Therefore, [a,b] refers to the window between y[-b] and y[-b-a] so  -b < i <= -b -a.

So the resolution is:
- [a,b]
- -b < i <= -b - a


so for lag 1:
- [1,0]  
-  0 < i <= -1 
- only observations -1 is included

so for lag 2:
- [1,1] 
-  -1 < i <= -2 
- only observations -2 is included

for rolling mean of 12 observations prior to the past 12 observations
- [12,12]
- -12 < i <= -24
- observations 13,14,15,16,17,18,19,20,21,22,23,24 are included

So in my view it is a consistent application.

**Comment by fkiraly** [comment]
ok, I'm assuming that all your inequalities are accidentally the wrong way round, above, but everything else is as you meant it.

I think I see where the confusion is coming from, then. `starting_at` is *not* included in the window? That seems highly counterintuitive, and inconsistent with python starting to count at zero, and finishing to count at `n-1`.
Should we not be consistent with `range`, and have the ends of the window, inclusive, being `y[-starting_at]` and `y[-starting_at-window_length+1]`?

**Comment by fkiraly** [comment]
& I think you fell into this trap yourself when you tried to translate

> including lagged window summaries of X by lags 12, 24 and window size 12 as exogeneous variables

a lag 1 has `starting_at` 0, so a lag 12 should have `starting_at` 11, and not 12.

I feel that proves that the current convention (exclusive of `starting_at`) might be a user confuser...

**Comment by danbartl** [comment]
> ok, I'm assuming that all your inequalities are accidentally the wrong way round, above, but everything else is as you meant it.

That is unfortunately correct.

> I think I see where the confusion is coming from, then. starting_at is not included in the window? That seems highly 
> counterintuitive, and inconsistent with python starting to count at zero, and finishing to count at n-1.
> Should we not be consistent with range, and have the ends of the window, inclusive, being y[-starting_at] and y[-starting_at-
> window_length+1]?

That was actually the orginal design, I changed it following the discussion with @ngupta23 , as you can see in the first few posts:

https://github.com/alan-turing-institute/sktime/pull/1924

The question is how do we want to access e.g. the week before the last week . Old notation was

"mean": ["mean", [7, 8]]

but we changed it after discussion in the thread to:

"mean": ["mean", [7, 7]]

which I kind of like, but that also means that lag 1 needs to be

"lag": ["lag", [1, 0]] 


> including lagged window summaries of X by lags 12, 24 and window size 12 as exogeneous variables

Ok I kind of interpreted "lagged window summaries of X by lags 12, 24 and window size 12 as exogeneous variables" since I do not understand the relevance of window length when combined with lags. So I actually showed an example of a feature of window length 12 shifted by 12, and window length 24 shifted by 12. 

Maybe you could make precise what kind of feature you expect here?

**Comment by fkiraly** [comment]
Discussion has been continued in PRs #2154, #2316, and #2396. Window summarizer is now implemented, and can be used as part of `make_reduction`.
