### ISSUE TITLE
[BUG] BoxCoxTransformer does not ignore y, possible also other SeriesToSeriesTransformers affected?

### ISSUE THREAD

**Issue by aiwalter** [alan-turing-institute/sktime#1725]
**Describe the bug**
BoxCoxTransformer does not ignore X, possible also other SeriesToSeriesTransformers affected?

Error:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-d6890121a38e> in <module>
     24 
     25 box = BoxCoxTransformer()
---> 26 box.fit(y_train, X_train)

~.\sktime\transformations\base.py in fit(self, X, y, Z)
    252             y,
    253             to_type=y_inner_mtype,
--> 254             as_scitype=y_input_scitype,
    255         )
    256 

~.\sktime\datatypes\_convert.py in convert_to(obj, to_type, as_scitype, store)
    185         to_type=to_type,
    186         as_scitype=as_scitype,
--> 187         store=store,
    188     )
    189 

~.\sktime\datatypes\_convert.py in convert(obj, from_type, to_type, as_scitype, store)
    122         )
    123 
--> 124     converted_obj = convert_dict[key](obj, store=store)
    125 
    126     return converted_obj

~.\sktime\datatypes\_series\_convert.py in convert_MvS_to_UvS_as_Series(obj, store)
     78 
     79     if len(obj.columns) != 1:
---> 80         raise ValueError("input must be univariate pd.DataFrame, with one column")
     81 
     82     if isinstance(store, dict):

ValueError: input must be univariate pd.DataFrame, with one column
```
**To Reproduce**

```python
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.transformations.series.boxcox import BoxCoxTransformer
from sktime.datasets import load_longley

y, X = load_longley()
y_train, y_test, X_train, X_test = temporal_train_test_split(y, X, test_size=4)

box = BoxCoxTransformer()
box.fit(y_train, X_train)
```
Its madatory that `X` is ignored, as pipelining is also broken now:
```python
pipe = TransformedTargetForecaster(steps=[
    ("box", BoxCoxTransformer()),
    ("forecaster", NaiveForecaster())
])
pipe.fit(y_train, X_train)
y_pred = pipe.predict(fh=fh, X=X_test)
```

**Expected behavior**
No exception

**Additional context**
Pipelining

**Versions**
main branch
</details>

@fkiraly fyi

**Comment by fkiraly** [comment]
Yes, I've verified this and understand the reason. I've PR'd a hotfix.
Only boxcox transformer is currently affected as per my understanding, see explanation in https://github.com/alan-turing-institute/sktime/pull/1724/

**Comment by fkiraly** [comment]
Here's the explanation:

Currently, passing multivariate `y` to the `BoxCoxTransformer` (refactored recently) will cause an error, since series-to-series transformers like it assume a univariate `y` by default, and a conversion is attempted to univariate `pd.Series` (which is impossible). This is unexpected, since the transformer ignores `y`.

This can be problematic in a `TransformedTargetPipeline` since there the forecaster's `X` - typically multivariate - is passed to the `y` of the transformers. (slightly surprising to me, but that's the status quo).

This implements a quick workaround, where the inner mtype for the `BoxCoxtransformer` is set to multivariate, that doesn't cause an error if a multivariate one is passed.

No other transformers are impacted currently, since `BoxCoxTransformer` is the only one refactored so far.

However, we need to think about how to fix this in the future. Options:
* assume multivariate `y` by default, this will do a silent input conversion (which may be superfluous but won't cause an error)
* introduce a tag on whether `y` is used internally, and in that case do not do a conversion at all (seems cleaner but introduces a new tag)

**Comment by fkiraly** [comment]
PS: in the issue title, it should be `y`, not `X`, right? Since it's about the `transforer.fit` argument `y`. It only happens in the forecaster pipeline that you pass the forecaster's `X` to the `y` argument.

**Comment by fkiraly** [comment]
the bug was introduced through the transformer refactor, btw.
Previously there wasn't a "strong" base class interface, so I suspect there might be a few hiccups until we have introduced a full test suite for trasnformers.

**Comment by aiwalter** [comment]
yes, in the new interface its `y`, but in the old its `X`.

**Comment by fkiraly** [comment]
I don't think that's right? In the old one it also was `y` in the transformer. It's just the pipeline logic which passes the forecaster's `X` to the transformer's `y`.

**Comment by aiwalter** [comment]
I think we just had `Z` and `X` in the old interface. Now we changed this to `Z-->X` and `X-->y` if I am not wrong?

**Comment by fkiraly** [comment]
? I think no?

previously, there was `Z`, `y`. We now changed `Z` to `X` so all transformers were consistent with argument naming.

**Comment by fkiraly** [comment]
no, you are actually right!

**Comment by fkiraly** [comment]
I made a mistake in the changelog describing this, I'll just go fix it too, there.
