### ISSUE TITLE
[BUG] unspecified bug with `KNeighborsTimeSeriesClassifier` in 0.8.0

### ISSUE THREAD

**Issue by Moooser** [alan-turing-institute/sktime#1825]
**Describe the bug**

**To Reproduce**

```python

# Version that works fine (V1)
from sktime.distances.elastic import dtw_distance
oneNNDTW = KNeighborsTimeSeriesClassifier(distance=dtw_distance)

# Version that works not as expected (V2)
from sktime.distances.elastic_cython import dtw_distance
oneNNDTW = KNeighborsTimeSeriesClassifier(distance=dtw_distance)
```

**Expected behavior**

**Additional context**

**Versions**
0.8.0

</details>

**Comment by fkiraly** [comment]
@Moooser, you are using 0.8.0 which is an older version.
Would you kindly be able to:
* check using 0.9.0
* provide the error message or unexpected behaviour
* provide expected behaviour
?

**Comment by TonyBagnall** [comment]
hi, this probably was not working because the C++ was not compiled. The problem no longer exists with number versions, the use cases are now 
# Version using string args
knn = KNeighborsTimeSeriesClassifier(distance="dtw")
# Version using native version. VERY SLOW!
from sktime.distances.elastic import dtw_distance
knn2 = KNeighborsTimeSeriesClassifier(distance=dtw_distance)
# Version usng numba version
from sktime.distances import dtw_distance
knn3 = KNeighborsTimeSeriesClassifier(distance=dtw_distance)
random_train_X = np.random.rand(10, 50)
random_train_y = np.random.randint(low=0, high=2, size=10)
random_test_X = np.random.rand(10, 50)
random_test_y = np.random.randint(low=0, high=2, size=10)
knn.fit(random_train_X, random_train_y)
knn2.fit(random_train_X, random_train_y)
knn3.fit(random_train_X, random_train_y)
print(" Random score =",knn.score(random_test_X,random_test_y))
print(" Random score =",knn2.score(random_test_X,random_test_y))
print(" Random score =",knn3.score(random_test_X,random_test_y))
