### ISSUE TITLE
[BUG] soft dependencies check may recommend wrong `pip install` command

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1906]
If the package dir is different from package name, the `sktime` soft dependencies wrapper may recommend to install the wrong package, because it recommends not `pip install pypi_name` but `pip install folder_name`. It should be the former and not the latter, but it is the latter, which may be wrong if the former or latter disagree.

The error message should change to the former.

Minimal example for the bug:
Running `import sktime.alignment.dtw_python`, when `dtw-python` is not installed in the python environment, produces error message "Please run: `pip install dtw`"

Expected behaviour under the same condition is a different error message: "Please run: `pip install dtw-python`"

**Comment by the-prof-paradox** [comment]
Hello, I would like to share my understandings about the issue.
I tired to replicate the mentioned bug by calling `test_check_soft_dependencies_raises_error()` function from
`/sktime/utils/_testing/tests/test_check_imports.py`

The message received :
No module named 'unavailable_module'. 'unavailable_module' is a soft dependency and not included in the sktime installation. Please run: `pip install unavailable_module`. To install all soft dependencies, run: `pip install sktime[all_extras]`

I don't understand what you mean by `folder_name` ?
The message simply asks to pip install the package name (string) passed as argument in `_check_soft_dependencies(*packages)`
from `/sktime/utils/validation/_dependencies.py`

I would like to understand more on:
1. What's difference between `pypi_name` and `folder_name` ?
Because as per my understanding, if we pass the pypi_name when calling `_check_soft_dependencies("pypi_name")` we will get the required recommendation.
2. Where are we using `_check_soft_dependencies("folder_name")` (if possible)? and can we simply achieve the goal by using "pypi_name" instead of "folder_name" while calling the _check_soft_dependencies ?


PS: I'm new to open source (would like to start my journey from this issue) and this is my first ever comment on github. So let me know if I am violating any code of conduct or if I am thinking in completely wrong direction. Thanks.

**Comment by fkiraly** [comment]
Welcome, @the-prof-paradox!

Sorry for lack of detail in the original post.

The crucial example in this case would be the `dtw-python` package, which is distinct from the `dtw` package.
`sktime` has a soft dependency on `dtw-python` (for alignment algorithms), but not on `dtw`.

Both packages, once installed, require one to write `import dtw.stuff`, since the package folder name for both is `dtw`.

The error message should say "please `pip install `dtw-ython`, if `dtw-python` is not installed and a user wants to use the dependent estimator `AlignerDTW`. But it does say "please `pip install dtw`", which is the wrong package.

**Comment by fkiraly** [comment]
I´ve added minimal example and actual vs expected behaviour to the original post now, thanks for pointing this out.

**Comment by fkiraly** [comment]
PS: simply changing the line to `_check_soft_dependencies("dtw-python")` does not work, since a check is done in the function by whether `import package_name` works.

**Comment by the-prof-paradox** [comment]
Thanks for the clarifications!

I would like to fix this issue so if there are no other asignees can you assign it to me?

**Comment by lmmentel** [comment]
All yours @the-prof-paradox !

**Comment by the-prof-paradox** [comment]
Hi @fkiraly 
How about we store the pypi packages name of the libraries in a dictionary like this:
```
_PYPI_PACKAGES = {
    "dtw":"dtw-python"
}
in the format:
dict = {
    "folder-name" : "pypi-name"
}
```
inside the `sktime/sktime/utils/validation/_dependencies.py` where `_check_soft_dependencies(*packages)` is defined.

because we need to map the folder-names to their PYPI names while recommending the pip install message.

I tried to dive deeper into code base and found that in `sktime/build_tools/azure/check_soft_dependencies.py` we have a `SOFT_DEPENDENCIES` dictionary. So I was thinking if we make the _PYPI_PACKAGES dictionary for each soft dependency mentioned here.

Then we will have all the correct pairs of pypi and libraries in a dictionary and in the message we can print `pip install {_PYPI_PACKAGES[package]}` if it exists else simply print "pip install {package}"

The list of all the soft dependencies I could find is: 
```
[
'dtw',
 'esig',
 'fbprophet',
 'hcrystalball',
 'matplotlib',
 'pmdarima',
 'stumpy',
 'tbats',
 'tsfresh'
]
```


Now, I would like to know:

1. Is this approach fine? 
2. If yes, then are there more soft dependencies with name conflicts like dtw and dtw-python? I manually tried to search for all the above mentioned soft dependencies on pypi.org and all looked like they won't have such conflicts except for `tsfresh` and `tsfresh-ppi` (just in case but tsfresh-ppi doesn't look relevant).
3. Are there more soft dependencies apart from the ones mentioned above?

**Comment by fkiraly** [comment]
> Is this approach fine?

I would see this only as a last resort if this cannot be inferred from the packages themselves somehow.

The main downside of this is that someone needs to *know* and *remember* that we've done this, and regularly check.
And any extender needs to be aware that this is happening - soft dependencies are added relatively frequently.

Generally, a solution that does not add to the maintenance, extension, and release process would be far preferred.

Surely this should be possible to automate somehow? (not sure though how)

> re there more soft dependencies apart from the ones mentioned above?

All should be there listed in the `all_extras` requirements, in `pyproject.toml`. I think there are more than those you listed.

**Comment by lmmentel** [comment]
I don't think there is a way of getting the top level module name from a package name without installing or at least downloading the package itself. The information is usually in `setup.py` like in the case of `dtw-python` https://github.com/DynamicTimeWarping/dtw-python/blob/81f26e1e052ef781d729e549fcd5e2b401e68af8/setup.py#L49 but can be in `pyproject.toml` in pypi or poetry flavors, so the task is not trivial at all. One solution would be to make a trip to pypi.org and download/install the package but that is poor solution since to throw an exception you would need to install a package dynamically. 

To be honest I don't understand the problem being solved here too well. When exactly is the soft dependency checker run? Why would we recommend installing a single package through pip?

**Comment by fkiraly** [comment]
> To be honest I don't understand the problem being solved here too well. When exactly is the soft dependency checker run? Why would we recommend installing a single package through pip?

I think when you are trying to import an estimator which uses a soft dependency inside.

>Why would we recommend installing a single package through pip?

"Dear user, if you want to use `MyEstimatorThatInterfacesPackageX`, please first `pip install package_X` which is a soft dependency (and that's the reason you haven't installed it yet when you installed `sktime` without soft dependencies)"

**Comment by fkiraly** [comment]
> I don't think there is a way of getting the top level module name from a package name without installing or at least downloading the package itself.

Well, if that's the case, then the `dict` idea is not too bad, it's easy to implement at least and better than the status quo.

I guess we should then make it easily configurable and overridable, with package name being top level module name by default, but you can specify both. Finding a good place for the config of overrides may be tricky.

**Comment by fkiraly** [comment]
> so the task is not trivial at all.

it is certainly non-trivial, but it seems so extremely generic that surely some good solutions must exist for it?

**Comment by fkiraly** [comment]
@the-prof-paradox, I assume your self-unassignment means you no longer wanted to work on this.

I have solved the issue now by adding an argument to the soft dependencies check function, #2545.
