### ISSUE TITLE
Re-fitting ContractedShapeletTransform inside a pipeline throws error [BUG]

### ISSUE THREAD

**Issue by prockenschaub** [alan-turing-institute/sktime#193]
**Describe the bug**
A pipeline including a `ContractedShapeletTransform` raises an error when fit twice in a row. 

**To Reproduce**
```python
import pandas as pd
from sktime.datasets import load_gunpoint
from sktime.transformers.shapelets import ContractedShapeletTransform
from sklearn.ensemble.forest import RandomForestClassifier
from sklearn.pipeline import Pipeline

X, y = load_gunpoint(split='TRAIN', return_X_y=True)

pipeline = Pipeline([
    ('st', ContractedShapeletTransform(time_limit_in_mins=0.1,
                                       num_candidates_to_sample_per_case=10,
                                       verbose=2)),
    ('rf', RandomForestClassifier(n_estimators=100)),
])

pipeline.fit(X, y)
# Runs fine
pipeline.fit(X, y)
# Exception: Trying to fit but shapelets already exist.
```

**Expected behavior**
Re-fit the shapelet transform without an error.

**Versions**
<details>

Windows-10-10.0.17763-SP0
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
NumPy 1.17.2
SciPy 1.2.2
sktime 0.3.1

</details>

**Comment by jasonlines** [comment]
Hi Patrick, thanks for raising the issues about the shapelet transform; I'll try to have a look at getting some fixes onto dev for them later this week when I get a chance. 

Just out of interest for this one specifically - what is your use case/what behaviour would you expect from fitting twice in a row? This particular error is by design and not a bug - it would deviate from our original tsml implementation (e.g. [mirroring line 502 here](https://github.com/uea-machine-learning/tsml/blob/master/src/main/java/timeseriesweka/filters/shapelet_transforms/ShapeletTransform.java) but raising the exception since fit/transform are disjoint in the sklearn pattern). 

I'll change the flair on this one as it's not a bug as-is but if you let me know a bit about the behaviour that you're after here then I'll certainly consider how I can work that in if it's appropriate

Thanks,

Jason

**Comment by prockenschaub** [comment]
Hi Jason, 

 

The error arose when I was using the shapelet transform as part of a pipeline within a leave-one-out setting. In this case, I wanted to refit the pipeline multiple times, each time for a new subset. 

 

The obvious workaround for this setting is to run clone(pipeline) within each run, which I believe is also what sklearn’s cross_val_score function does. 

 

However, I personally would have expected calling fit a second time to just overwrite all previous results and run a fresh fit. I believe that is in line with how sklearn’s estimators generally behave but I guess this mostly comes down to flavour. 

 

Does that make sense?

 

P

**Comment by jasonlines** [comment]
Hi Patrick,

Thanks for the explanation - makes perfect sense :) 

I'm still quite new to the ways of sklearn so thanks for the context too. I would have expected a loocv to build new transforms rather than reusing the same transform (to avoid any potential cross-contamination). However, if that's not the default in sklean then it should be able to handle that.

For context, the issue in TSML is that `fit`/`transform` are not separate methods, so calling `process` does that shapelet extraction _and_ transforms the input data, or calling it a second time just does the transform and ignores the extraction step. This informed my decision to just raise an error if sktime's `fit` is called twice. However, in light of your observations then I think it would make more sense to allow fit to be called a second time and overwrite the original transform (perhaps providing a mutable warning to the user that the shapelets are being overwritten)

I'll have a think but thanks for the explanation,

Jason

**Comment by mloning** [comment]
This now works: 

```python
import pandas as pd
from sktime.datasets import load_gunpoint
from sktime.transformations.panel.shapelets import ContractedShapeletTransform
from sklearn.ensemble.forest import RandomForestClassifier
from sklearn.pipeline import Pipeline

X, y = load_gunpoint(split='train', return_X_y=True)

pipeline = Pipeline([
    ('st', ContractedShapeletTransform(time_contract_in_mins=0.1,
                                       num_candidates_to_sample_per_case=10,
                                       verbose=2)),
    ('rf', RandomForestClassifier(n_estimators=100)),
])

pipeline.fit(X, y)
pipeline.fit(X, y)
```
