### ISSUE TITLE
[ENH] design - init, parameter check, dynamic tags - conflicting interface requirements

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#2573]
We need to have a design decision on conflicting elements of our current interface specification.

These are:

1. `__init__` should contain no logic for input checking, and optimally no other logic. Such logic should be placed at the start of `_fit`
2. dynamic tags need to be set in the `__init__`, since tags are read at the start of the `fit` call which precedes the `_fit` call
3. we have the `fit_is_empty` tag, which can mean that `_fit` is never called for a given estimator, as well as estimators/object types that have no `fit` (such as distances)

Here, 1. conflucts with 2. and with 3., but 2. and 3. do not conflict with each other (I think).

I feel we need to think about potential ways to resolve this situation.

Related: https://github.com/alan-turing-institute/sktime/issues/1798

**Comment by fkiraly** [comment]
FYI @lmmentel who highlighted this.
FYI @miraep8 who recently thought about it in #2540 and #2458.
FYI @aiwalter, @TonyBagnall

**Comment by fkiraly** [comment]
My personal opinion is, 1. should go.
The requirement of 1. is coming from `sklearn`, the rationale being that calling `fit` multiple times, and possibly `set_params` in-between, should be possible and result in the same state as after the last `fit` call.

`sklearn` has no choice in this imo, since there is no "boilerplate" layer and all the checks etc need to be implemented by a user every ime they write an estimator.
We, however, do have a choice - we can call parameter setting and checking logic from the layer between `fit` and `_fit`.

Like this: https://github.com/alan-turing-institute/sktime/pull/2562

We still would be `sklearn` compatible, since the external logic would be indistinguishable.

There is one - positive! - exception:
with this, the user receives feedback at *specification* of an invalid estimator, not just at `fit` which is later.
This would be in line with the principle "give feedback on invalid input as early as possible", and `sklearn` is *not*  in line with that!

**Comment by fkiraly** [comment]
a more extreme variant of this would be dedicated parameter check methods, as here:
https://github.com/alan-turing-institute/sktime/issues/1798
though that might be overkill.

**Comment by miraep8** [comment]
Out of curiosity - are dynamic tags a relative new thing (ie essentially only used in `MultiplexForecaster`?) or is it a more wide spread thing.  (I am more familiar with `MultiplexForecaster` at the moment... haven't directly seen it other places, but thought I would ask!)  If it is only really seen in `MultiplexForecaster` - then as I mentioned in #2458 it is possible to not dynamically set tags in `MultiplexForecaster` (at least it is not necessary for `fit` to work)-in fact #2570 provides a way to do this by bypassing the fit call on `MultiplexForecaster`.  Though as #2570 stands it doesn't completely solve the other other issue you mentioned in relation to dynamically setting tags:

>However, I see a problem with retrieval and querying, so while tempting I fear this might not work.
The problem arises because the tags on the outside would no longer be "true", so they cannot be relied upon anymore for giving correct answers about properties.
>
>For example, let's assume a user asking a pipeline "can you work with multivariate data"? The multiplexer would give the wrong answer.
It would also give the wrong answer if you further put the multiplexer in a pipeline, to the other parts of the pipeline that now wrap the multiplexer.
Another example, let's say we loop through forecaster instances in testing. We want to pass multivariate data to all forecasters that claim they are multivariate and check they do not raise the error. The multiplexer would then fail the test, because the inner forecaster cannot deal with the multivariate data, but the test would think that it should be able to.

But.... I think it could be an easy change for the new delegator approach to solve this problem as well!!! (If you think it is worth looking into!)

**Comment by fkiraly** [comment]
> is it a more wide spread thing.

It is fairly wide-spread, it happens in composites. Search for `clone_tags` or `set_tag` to find more instances.

**Comment by fkiraly** [comment]
@aiwalter, you commented on a couple PR on content of the `__init__` - do you want to add something here?
This is precisely the topic...

**Comment by lmmentel** [comment]
Since it is not the first time the *same* question regarding design surfaces we need a clearer design direction on this. As much as am I'm not happy with all the design choices of sklearn api it is at least very clear on what it takes to compatible an why. Not to mention test of the years. We should take this opportunity to define the api design principles for sktime and wither follow sklearn fully, partially or come up with our own api design.

My personal opinion would go towards adopting sklearn fully with all it's tradeoffs since that is the _de facto_ standard.

**Comment by fkiraly** [comment]
> My personal opinion would go towards adopting sklearn fully with all it's tradeoffs since that is the de facto standard.

I think that´s not possible since we are a package for time series and sklearn is not. So there is some degree we need to depart from sklearn. "adopting sklearn fully" has a nice ring to it but what is there to "adopt"? The supervised regression interface, e.g., do you want to turn the forecasters into sklearn compatible supervised regressors? Probably not. So, would appreciate this spelled out more concretely.

**Comment by fkiraly** [comment]
related PR: https://github.com/alan-turing-institute/sktime/pull/2835

**Comment by fkiraly** [comment]
From discussion with @aiwalter today:

we agreed on that "`__init__` has no content" is a side artefact of the "no boilerplate layer" design in `scikit-learn`, it is, in parts, an internal (implementer facing) requirement.

The *really important* requirement is the user/external facing one, "`set_params` leaves the same state as `__init__` would", also see PR https://github.com/alan-turing-institute/sktime/pull/2835.

So, going forward, we will adopt the latter, possibly restricting the things that should be in `__init__` (but without restricting it to "nothing"). I'll make a PR that updates the extension templates.

**Comment by fkiraly** [comment]
This PR implements this: https://github.com/alan-turing-institute/sktime/pull/3010
(I think? please comment)

**Comment by fkiraly** [comment]
update on this for how the design ended up being, for use in `skbase` design discussions:

`sktime` has dropped requirement 1.

The `fit` boilerplate calls `reset`, which calls `__init__`,  thus ensuring that tag setting logic is also executed in any parameter state change.

It also allows parameter validity checking directly in `__init__` in the same way,  which is de-facto contained in some estimators.
