### ISSUE TITLE
[BUG] remove unused `interval_width` param from `Prophet`

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#2626]
The `interval_width` parameter of `Prophet` is not used (later overridden by an interval width in `predict_interval`), and not mentioned in the docstring.

I think it should simply be removed as an `__init__` argument - initialization logic can be replaced by the default value, if needed.

Do I understand the logic correctly, @kejsitake? Would you agree with this?

**Comment by phershbe** [comment]
@fkiraly If you decide that this change should be implemented, I can do this if you would like. I'm relatively new to open source and have never worked as a programmer, I am fairly confident in my ability to do algorithms and to read and write code though. I found the file in the codebase.

**Comment by fkiraly** [comment]
well, it's a two- or few-line change, so it would be great if you could make a draft PR and we see if anything breaks - that's also valuable information here. Thanks!

Before merging, I'd still wait a few days for @kejsitake to respond if she find the time to look at this.

But, since it's just a few lines, I see no harm in getting started, under the proviso that it might not get merged in the end.

**Comment by phershbe** [comment]
@fkiraly @kejsitake Okay, great, the draft PR is above. No problem if it does not get merged in the end, I'm here to learn and to contribute to the project.

You will want to check out the changes to make sure that they make sense, as I don't have so much experience yet. Am I in the correct file? Because interval_width exists in two other files too. In the file that I changed, I didn't delete "interval_width=1 - self.alpha" in the "_instantiate_model" method, is that correct?

In the interest of getting this up quickly, I have not run the CI tests locally yet. It's late here, I will do that tomorrow though.

**Comment by kejsitake** [comment]
Hi @phershbe and thank you for considering contributing to sktime!

I recall there being something weird about prophet requiring the `interval_width` argument at the time of class initialization, different from the other forecasters that required it only when calling predict_int, but I think that this change shouldn't impact any of that.

**Comment by fkiraly** [comment]
> but I think that this change shouldn't impact any of that.

Yes, that's what I also thought, @kejsitake, it should be fine if we feed it some parameter, it doesn't need to be coming from `__init__`.
