### ISSUE TITLE
[ENH] test_update_predict_predicted_index should have no gaps between data passed in fit and the consecutive update steps.

### ISSUE THREAD

**Issue by ltsaprounis** [alan-turing-institute/sktime#2700]
**Is your feature request related to a problem? Please describe.**
The forecasting test [`test_update_predict_predicted_index`](https://github.com/alan-turing-institute/sktime/blob/df683766f4af7fd7fbe339fbf306d7a560827574/sktime/forecasting/tests/test_all_forecasters.py#L520) does the following:
1. splits a time series y in `y_train` and `y_test`. 
2. fits a forecasting algorithm using `y_train`
3. calls `update_predict` on the fitted forecaster using `y_test` and a `SlidingWindowSplitter`. 

The problem with the test is that the first non-trivial update call uses data that are more than one time step ahead than the data passed in fit. As a result when we try to reconcile `y_train` and the subset of `y_test` from the splitter the resulting time series has gaps and frequency None. For some reason this was not causing any forecasting algorithm to break apart from `BaggingForecaster` in #2248 and in only 2 test cases ([see CI log](https://github.com/alan-turing-institute/sktime/runs/6397105019?check_suite_focus=true#step:7:47103)).

The following code reproduces the behaviour of the test:
```python
from sktime.utils._testing.series import _make_series
from sktime.forecasting.model_selection import (
    SlidingWindowSplitter,
    temporal_train_test_split,
)

n_columns = 1
fh_int_oos = [2, 5]
window_length = 1
step_length = 5

y = _make_series(n_columns=n_columns, all_positive=True, index_type="datetime")
y_train, y_test = temporal_train_test_split(y)
cv = SlidingWindowSplitter(
    fh_int_oos,
    window_length=window_length,
    step_length=step_length,
    start_with_window=False,
)

print(f"max date seen during fit: {y_train.index.max()}")
counter = 0
for train_idx, test_idx in cv.split(y_test):
    print(f"split {counter} min date seen during update: {y_test.iloc[train_idx].index.min()}")
    counter += 1

# Prints:
# max date seen during fit: 2000-02-06 00:00:00
# split 0 min date seen during update: NaT
# split 1 min date seen during update: 2000-02-11 00:00:00
```

**Describe the solution you'd like**
Having a complete time series is a fair requirement from a forecasting algorithm, the test should reflect this.
Using the `ExpandingWindowSlicer` instead of the `SlidingWindowSplitter` will fix this.

**Describe alternatives you've considered**
Not implementing BaggingForecaster

⚠️ **Disclaimer** ⚠️
There's a good chance that my conclusion that the test needs some changes is wrong and there's a valid reason for it being that way.

**Comment by ltsaprounis** [comment]
FYI - @khrapovs and @fkiraly

**Comment by fkiraly** [comment]
How odd. It looks like you found out why we have problems with `test_update_predict_predicted_index` repeatedly.
Well, this is the third reason, I think I removed two other reasons here https://github.com/alan-turing-institute/sktime/issues/2555 and here https://github.com/alan-turing-institute/sktime/pull/2466 ...

This test is cursed.

I think there are two topics here: a design question, and pragmatic next steps.

Regarding pragmatic next steps: I think your PR is perfectly appropriate as a fix, until we have answered the design questions. Since it moves intention and logic back to the case `sktime` supports and which is widely tested, that of regular time stamp indices (I intentionally don't say "continuous" since this term has multiple, reserved meanings).

Regarding design questions: having read this three times, I am not sure whether this is:

* a problem with the test logic, e.g., we do not need/want to test that esimators are fine with irregular data
* a problem with the test implementation, i.e., whether the intention was to have what you changed it to
* a problem with the framework, i.e., that it does not mitigate the impact when data becomes irregular like this

This seems to boil down to some design questions related to irregular data:

* should all forecaster estimators be fine with irregular data? E.g., if received in `update` like this.
* if forecasters are not fine with irregular data, but receive a time stamp "on the grid", should the "updating memory" functionality of the framework perhaps fill in NAs? Then, forecasters which can deal with NAs but not irregular data would still be ok. We have an encapsulated entry point for the memory update since this PR https://github.com/alan-turing-institute/sktime/pull/2412, so this could be addressed there.
* if some forecasters can deal with irregular data while others cannot, should we introduce a tag for it, and have conditional behaviour and testing?

From answers to the above, we can derive:

* framework implementation and logic implementation targets
* an answer to "what the `test_update_predict_predicted_index` test should do
* whether we need additional tests related to irregular data

**Comment by fkiraly** [comment]
I think this is deep and consequential enough to be an agenda point at the next regular dev meeting?

**Comment by ltsaprounis** [comment]
I think this is deep and consequential enough to be an agenda point at the next regular dev meeting?

I agree! I personally like the tag option for irregular time series.

**Comment by khrapovs** [comment]
Kudos to that. I am working on irregular time series. For now only in splitters though.
