### ISSUE TITLE
[ENH] Adding pytest-randomly to tests

### ISSUE THREAD

**Issue by aiwalter** [alan-turing-institute/sktime#2766]
**Is your feature request related to a problem? Please describe.**
Would be nice to add this to our test execution: https://github.com/pytest-dev/pytest-randomly
It can help to detect side effects of tests by randomly shuffle test order on execution.

**Comment by fkiraly** [comment]
Good idea! We had that before!

One minor issue though is, we have two tests that need to be run in sequence, since they test for a specific instance of side effects across tests: `test_no_cross_test_side_effects_part1` and `test_no_cross_test_side_effects_part2`.

They won't fail if you change the sequence, but will catch failures only if run in the right sequence.

**Comment by fkiraly** [comment]
>maybe we dont need them then anymore, or can refactor them?

Well, I would argue we still need them, since permutation does not necessarily cause a failure under the condition that is tested for here, i.e., if estimator states are remembered across tests.
The pair of tests guarantees a failure (if executed in the right order) under that condition.
