### ISSUE TITLE
[ENH] BaseGridSearch to have param error_score like in sklearn

### ISSUE THREAD

**Issue by aiwalter** [alan-turing-institute/sktime#2891]
**Is your feature request related to a problem? Please describe.**
When fitting a grid search with a pipeline in `sktime`, it can happen that the estimator or one of the transformers raises an exception for some combinations of the params. I personally faced this often when a transformer like box cox introduces negative values, but the following transformer/estimator can only use `>0` or `>=0 ` values. This is especially a problem when you want to apply an `optionalPassthrough` to the transformers.

**Describe the solution you'd like**
For this, in `sklearn` there is a param `error_score`:
```error_score‘raise’ or numeric, default=np.nan
Value to assign to the score if an error occurs in estimator fitting. If set to ‘raise’, the error is raised. If a numeric value is given, FitFailedWarning is raised. This parameter does not affect the refit step, which will always raise the error.`
```
https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html

We also should have this as it can be quite cumbersome in a bigger grid to not get any exception.

**Comment by ilkersigirci** [comment]
Why sktime didn't implement evaluate and grid search mechanism like in the sklearn? I think the way [pycaret](https://github.com/pycaret/pycaret/blob/master/pycaret/utils/time_series/forecasting/model_selection.py) handles this cross_validation mechanism is much more convenient since it closely follows sklearn structure. What would you think about this?

**Comment by aiwalter** [comment]
@ilkersigirci can you be more precise with what you think is missing or should be different?

**Comment by ilkersigirci** [comment]
As @ngupta23 pointed out in the docstring of the `fit_and_score` method:

"Fits the pipeline on a single train split and scores on the test split 
 Similar to _fit_and_score from `sklearn` (and to some extent `sktime`).Difference is that sklearn operates on a single fold only, whereas sktime operates on all cv folds."

Doing sklearn way enable us to parallise each split in cross_validation function and hopefully reduce its execution time. However, for `strategy="update"` 
, we might handle it separately.

Actually the above  two methods are just design choices, one not strictly better than other but since the goal of sktime is closely follow sklearn structure as possible, I wonder why there is different design in the cross_validation(evaluation) case.
