### ISSUE TITLE
[BUG] failing codecov step in CI - certificate expired

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#3057]
The codecov step in CI is failing with the following:

```
Run codecov/codecov-action@v2
==> linux OS detected
Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1502:34)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:711:12)
```

**Comment by miraep8** [comment]
I wonder if it has something to do with the some of the node package manager stuff being out of date for codecov v2 vs v3? I just tested out switching from v2 to v3 in #3059 and it seems to work ok? *(Note - I deleted all the actual tests to just try it out quickly so I wouldn't recommend merging that, but will put them back now and run the full test suite with v3 rather than v2)*

**Comment by fkiraly** [comment]
hm... seems to work again, so I suppose, issue closed.
