### ISSUE TITLE
[BUG] clone is not working correctly on ExpandingWindowSplitter

### ISSUE THREAD

**Issue by SzymonStolarski** [alan-turing-institute/sktime#3119]
**Describe the bug**

- Sklearn's `clone()` function is not working correctly on `ExpandingWindowSplitter`
- The `window_length` parameter is not copied
- `initial_window` is copied into `window_length` which is fine according to docstrings, however is counterintuitive and incompatible with `clone()`
- This generates problems when cloning models that have cross-validation embeded
- Example: `MultiplexForecaster` combined with `ForecastingGridSearchCV` cannot be evaluated using sktime's `evaluate()`

**To Reproduce**

```python
from sktime.forecasting.model_selection import ExpandingWindowSplitter
from sklearn.base import clone


cv = ExpandingWindowSplitter(
    start_with_window=True,
    initial_window=10,
    fh=[1])

print('pre-clone: ', cv.__dict__)
print('post-clone: ', clone(cv).__dict__)
```
```
pre-clone:  {'step_length': 1, 'start_with_window': True, 'initial_window': None, 'window_length': 10, 'fh': [1]}
post-clone:  {'step_length': 1, 'start_with_window': True, 'initial_window': None, 'window_length': None, 'fh': [1]}
```

**Expected behavior**

Pre-clone and post-clone CVs should be identical.

**Additional context**

**Versions**
<details>

System:
    python: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0]
executable: /local_disk0/pythonVirtualEnvDirs/virtualEnv-3d157b3d-b81c-4d78-b9fe-a70430ada65a/bin/python
   machine: Linux-5.4.0-1086-azure-x86_64-with-glibc2.29

Python dependencies:
          pip: 21.0.1
   setuptools: 52.0.0
      sklearn: 0.24.1
       sktime: 0.13.0
  statsmodels: 0.13.1
        numpy: 1.22.4
        scipy: 1.6.2
       pandas: 1.2.4
   matplotlib: 3.4.2
       joblib: 1.0.1
        numba: 0.55.2
     pmdarima: 1.8.4
      tsfresh: None
</details>

**Comment by fkiraly** [comment]
Yes, I can confirm that.

I wondered why the tests do not catch this, since all objects meant to be sklearn compatible are run through the test suite which tests precisely this.

The reason is that `BaseSplitter` has only recently been moved to inherit from `BaseObject`, and is not in the registry of base objects, so while going through the package, the splitters are not discovered by the tests.

A secondary issue is that the tests do not distinguish between fittable and non-fittable objects (like splitters), so simply adding the splitters to the registry would make them fail the tests that have to do with `fit`. We may have to think about this carefully, how to solve the test issue.

Regarding the issue with the splitters, this should be easy to solve by ensuring that self writes happen properly.

**Comment by fkiraly** [comment]
I added the general issue here: https://github.com/alan-turing-institute/sktime/issues/3120

This issue is for fixing `ExpandingWindowSplitter` only.

**Comment by fkiraly** [comment]
Fix here: https://github.com/alan-turing-institute/sktime/pull/3121
