### ISSUE TITLE
Problem with load_gunpoint_dataframe

### ISSUE THREAD

**Issue by hfawaz** [alan-turing-institute/sktime#38]
Thank you for sharing this project ! 

I was testing ```load_gunpoint_dataframe``` and got an ```str``` as type for ```x_train```. 

I used ```X_train, y_train = load_gunpoint_dataframe(split='TRAIN', return_X_y=True)```. 

Thanks

**Comment by jasonlines** [comment]
Hi Hassan,

Thanks for the heads up. Your usage of this method isn't quite correct, hence the strange behaviour, but it is surprising that this didn't raise an error! So thanks for bringing this to our attention. Briefly to explain, the idea behind that method is to allow a user to either:

a) return a single dataframe containing X and Y (where `return_X_y = True`). For n columns, the first n-1 columns each represent a dimension in the data, and the nth column will be the y values. We have this functionality to allow for the high-level interface with tasks 

b) return a dataframe for X and a separate 1d array containing Y (where `return_X_y = True`). This usage is low-level and more typical for a traditional sklearn approach (e.g. calling fit(X,y))

In your code you've used the option to return a single dataframe containing X and y combined (`return_X_y = True`) but unpacked it into two variables. This is why it isn't working correctly, but it is somewhat strange that it worked at all! It seems that unpacking the single dataframe into two variables has, rather than throwing an exception, made the variables correspond to names of the first and second columns in the dataframe. That is a bit strange really and not desirable so thanks for letting us know.

To solve your problem however, if you want a separate X and y then setting `return_X_y = False` should do it. Otherwise, if you'd like a composite dataframe containing both X and y then you just need to assign the result of the method to a single variable.

Thanks,

Jason
