### ISSUE TITLE
Provide tools for directly downloading the datasets from timeseriesclassification.com

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#425]
**Is your feature request related to a problem? Please describe.**

it would be useful for users to be able to download the classification/regression problems directly from timeseriesclassification.com in code. Apparently tslearn does this, and it seems like a good idea

**Describe the solution you'd like**
I'm not sure where it should be located, perhaps with the load data tools

**Describe alternatives you've considered**
You can manually download the data, but this is labour intensive and means you need to confront the data format, when perhaps you do not need to.

**Comment by Emiliathewolf** [comment]
Hey can I have this?

**Comment by TonyBagnall** [comment]
Yep 👍

**Comment by mloning** [comment]
I think we want some function to download data sets  and save them in a default location (i.e. `sktime/datasets/data`) so that we can simply load them the next time we need them.

This may help:
* Please check out https://tslearn.readthedocs.io/en/stable/gen_modules/datasets/tslearn.datasets.UCR_UEA_datasets.html#tslearn.datasets.UCR_UEA_datasets
* This may also be helpful https://github.com/fastai/fastai/blob/e34fee816f5dcbf05a9bc9b44e617902a52549fc/fastai/data/external.py#L243

**Comment by Emiliathewolf** [comment]
Thanks, I'll have a look at them

**Comment by mloning** [comment]
Closed by #430
