### ISSUE TITLE
Restructuring of the utils directory

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#434]
this directory contains a lot of legacy code that could usefully be tidied up and restructured. This is ongoing work with UEA project students, and we will list changes as we do them, this is an issue simply to help manage it. Suggestions welcome

this is the starting structure
![image](https://user-images.githubusercontent.com/9594042/96365996-a0e4ef00-113c-11eb-8b96-24c11777f279.png)

1. All these files need better commenting, including authorship 
2. files boxcox, seasonality and time_series are all related to forecasting and can be removed or refactored. 
3. check_imports, comparison, confidence are small utility functions, which means they should be here, but possibly better grouped/different file structure
4. load_data and results_writing can be here, but need tidying and refactoring
5. Directory plotting is empty
6. Directory _testing, tests and _testing/tests needs tidying up 
7. Directory validation: thje role of this directory needs clarifying
8. Directory maintenance contains show_versions, which is used in sktime/__init__.py, although the init accesses a protected file

**Comment by whackteachers** [comment]
Hi I am Jason. Got some questions on this.
For 2, I see that there are still usages on them, how do I handle the dependencies on them?
similarly when restructuring the directory, I assume I have to refactor the usages as well?

**Comment by TonyBagnall** [comment]
Hi jason, can we discuss this on teams? I am not expecting you to do this without guidance, the above is for discussion

**Comment by whackteachers** [comment]
sure

**Comment by mloning** [comment]
Thanks @TonyBagnall! 

I agree with most of this! I'm planning to make a new minor release, and then work towards a new major release by adding transformer types (#420) and restructuring this. 

5. Plotting isn't empty but can be made a file rather than a module (there's a function in the __init__)
6. Files/module that start with "test" are recognised by pytest as unit tests. The module "_testing" contains utils for running unit tests, some of which are themselves tested. I had a quick look at the module itself which seems fairly organised I think.
7. contains input checks and is also fairly organised I think

Adding docstrings to the top of the files in addition to authorship would help clarify the purpose. For authorship please also use CODEOWNERS in the root dir.

**Comment by mloning** [comment]
This should now be fixed in the new release https://github.com/alan-turing-institute/sktime/releases/tag/v0.5.0
