### ISSUE TITLE
Track run time of AutoARIMA

### ISSUE THREAD

**Issue by ahmadhfs** [alan-turing-institute/sktime#436]
**Is your feature request related to a problem? Please describe.**
I was working on a project and ran the AutoARIMA model ,which took long time to finish ,and could not get a sense of how long would it takes or at which stage the algorithm is currently running.

**Describe the solution you'd like**
Here are some suggestions:
1. Calculating the complexity of the algorithm ( O(N) ) and multiplying it by the length of data/parameters.
2. Performing trials on different datasets with recording its execution time and averaging it ( Two routes: 1- Since hardware are different, the algorithm could perform a small test with a built-in dataset to infer the execution time from it. 2- By doing the trials on bunches of computers and averaging)
3. Or simply by printing after each stage or updating a bar with that stage.

**Comment by mloning** [comment]
Hi @ahmadhfs, could you tell us a little more about what you have in mind to track the time to fit and predict? Please fill in the template of the issue accordingly, putting everything into the title isn't very helpful. 

We have been thinking about implementing time contracting for algorithms, so that users can set a time for how long to run an algorithm but this requires substantial work and we haven't started to implement this more widely, however some of the classification algorithms do support it.

**Comment by mloning** [comment]
I'll close this for now but feel free to re-open it if you want to discuss this further!

**Comment by ahmadhfs** [comment]
I filled the templte above. Thank you @mloning

**Comment by mloning** [comment]
For the AutoARIMA model we use pmdarima's implementation. If you take a look at the docstring, you can easily find the `trace` parameter which gives you some more details about what's happening internally. If you want more than that, please open an issue on their GitHub account. 

```python
from sktime.forecasting.all import *
f = AutoARIMA(suppress_warnings=True, trace=1)
y = load_airline()
f.fit(y)
```

**Comment by mloning** [comment]
I'll close this for now but feel free to re-open it if you want to discuss this further!
