### ISSUE TITLE
[DOC] ForecastingHorizon is not in API reference of latest version of Docs

### ISSUE THREAD

**Issue by evanmiller29** [alan-turing-institute/sktime#443]
#### Describe the issue linked to the documentation

ForecastingHorizon is mentioned in the [forecasting example](https://www.sktime.org/en/latest/examples/01_forecasting.html ) but there isn't a mention of it in the [API reference](https://www.sktime.org/en/latest/api_reference.html) 

I found this when I tried to debug an error trying to used it in my own work. 

If there's a simple way of adding this I'm happy to do it, and I'd like to rewrite the imports for the forecasting tutorial too.
`from sktime.forecasting.all import *` isn't really best practice and makes it difficult to understand the underlying folder structure of sktime without going to github .

#### Suggest a potential alternative/fix

Add ForecastingHorizon to API reference and make forecasting imports more informative. I'm happy to pick this up

**Comment by mloning** [comment]
Thanks @evanmiller29, good catch, added it in #444! It was easy to fix, but take a look at the PR to find out how the docs work in case you're not familiar with it. 

As far as I understand, there's nothing dangerous about `sktime.forecasting.all import *`. Fastai have proposed it as a compromise between easy importing and managing name space collisions. You can always use auto-complete to see what folders/files are there, no? But I'm happy to be convinced otherwise and replace it in the notebooks with explicit imports.

**Comment by evanmiller29** [comment]
Hey yeah dangerous might have been a bit of an extreme way to describe it!

I know fastai does this but sklearn (where this package is inspired from)
is always very direct in where the imports come from. probably because they
have so many different areas of functionality and import * might create
some performance/namespace issues.

But the benefit of doing direct imports means that the people get a good
understanding of the underlying modules behind the package. And at the
worst case they can always import * if they really want to.

For instance in one of my projects I just read in smape_loss but since the
forecasting notebook just read imported * from sktime I had to look on
GitHub to understand the package structure to be able to find where
smape_loss was and read that in
