### ISSUE TITLE
Replace nested pd.DataFrame with awkward-array

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#448]
We currently still support the nested pd.DataFrame with series in cells for panel data in addition to 3d numpy arrays (see #402). While very flexible, the nested pd.DataFrame is slow and continues to cause a lot of bugs and confusion on the side of users and contributors.

I propose to replace nested pd.DataFrame with awkward-array for time-heterogeneous data and deprecate and remove the nested pd.DataFrame.

More details in our enhancement proposal: https://github.com/sktime/enhancement-proposals/blob/master/steps/02_data_container/step.md and #15

**Comment by fkiraly** [comment]
Disagree with deprecation - I would still suggest to try to support it, in addition.

I also think we need to take care of the "multiple input types" issue cleanly once and for all, including light-weight architecture for type conversions and type checks. See discussion at the end of #420.

**Comment by mloning** [comment]
The nested pd.DataFrame causes a lot of headaches all over the place (conversions, input checks, loading, checking for equality, obtaining shapes, etc, etc), besides that most operations on it are very slow. I'd really prefer to deprecate it in the long run.

**Comment by fkiraly** [comment]
> I'd really prefer to deprecate it in the long run.

So do I, but I don't see a viable alternative yet for samples of unequally sampled, unequal length time series with named variables.

As long as deprecating it would mean deprecating an entire scitype central to the sktime vision, I'll be against it.

**Comment by SaddamHussain84** [comment]
I have data frame whose features are monthly electricity consumption of thousand different users and target variable is customer is either healthy or involved in theft...My data format is typical pandas data frame as you see titanic data set having number of features and in the end survival as target...
since electricity consumption data is time series, how to convert pandas data frame to suitable sktime format
Can you help me how to convert pandas data frame having X as features and y as target into sktime....

**Comment by mloning** [comment]
Hi @SaddamHussain84 that's probably best discussed in a separate issue, please create a new one and add some simple example data, that would be most helpful to answer your question!

**Comment by harahu** [comment]
> > I'd really prefer to deprecate it in the long run.
> 
> So do I, but I don't see a viable alternative yet for samples of unequally sampled, unequal length time series with named variables.
> 
> As long as deprecating it would mean deprecating an entire scitype central to the sktime vision, I'll be against it.

About that. I am considering going from a custom data pipeline implementation based on pandas to using sktime for just this kind of data:

- Multi-channel
- Multi-object (panel data)
- Time heterogeneous (unequal spacing between samples within and across channels)
- Ragged (panels of different duration, both in time and sample count)
- Indexed by datetime rather than int

Until now I haven't dared make the move, because I haven't seen examples of this kind of data in use with sktime. If it was possible, sktime seems to be just the platform I need.

Is this well supported in sktime today? Have you gotten closer to figuring out if this will remain a goal for the project?

I really miss a serious toolbox for generalized time series data that does cover more than the "ordinal sequence" subset of this space.

**Comment by mloning** [comment]
Hi @harahu, unfortunately we haven't made much progress in that direction. The fundamental challenge is the data container. awkward-array seems to be the most promising solution. The other challenge is extending algorithms to handle that kind of data. 

sktime does offer some support for multivariate panel data (multi-channel and multi-object), but not time-heterogenous data. 

What other tools have you worked with so far to handle that kind of data?

**Comment by fkiraly** [comment]
The nested `pd.DataFrame` structure was meant to address exactly that use case!
I believe it's quite common in "serious" applications, equal length, equal time points etc is often a bit artificial...

Indeed the problem is the data container representation, nested `pd.DataFrame` is a bit of a hack.
Though, getting a clean container plus interface would hinge on volunteer contributions - which may be unlikely in the close future, because most people like to work on exciting methodology rather than on the data back-end...

**Comment by fkiraly** [comment]
... would you be interested to help, @harahu?

**Comment by harahu** [comment]
@mloning:
> What other tools have you worked with so far to handle that kind of data?

Mostly custom developed tooling, based on pandas, where calculations are done by first "translating" the general data formats mentioned above to more limited formats expected by mainstream time series tooling. Not highly efficient. In other words, I have never actually experienced a tool set that makes it easy to work with this kind of data. A semi-exception might be [traces](https://github.com/datascopeanalytics/traces), by @stringertheory et al. They have a great API design that makes working with ragged, time heterogeneous data easy, but I don't think the internals make it scalable to truly big datasets and massive computation. 

@fkiraly:
> I believe it's quite common in "serious" applications, equal length, equal time points etc is often a bit artificial...

That is my experience as well. My domain is sensor data from process industry. It is quite common for me to be looking at datasets that span multiple years, consisting of a mix of high and low frequency channels. It is then common to represent it in a "sparse" way, where you only get a reading when there is an actual change in the signal, to avoid low frequency channels eating up valuable memory. The assumption is that you can usually just forward fill the last seen value to any time point to get a continuously valid signal. Going from this format to supported formats in most time series libraries is painful.

> Indeed the problem is the data container representation, nested `pd.DataFrame` is a bit of a hack.
> Though, getting a clean container plus interface would hinge on volunteer contributions - which may be unlikely in the close future, because most people like to work on exciting methodology rather than on the data back-end...
> ... would you be interested to help, @harahu?

I would love to, but if I am being honest with myself I am merely a heavy user of the Pandas API, I don't know a lot about what goes on under the hood. I don't know much about the alternatives you are evaluating either, like awkward arrays. I might be able to help out if there is anything concrete you need doing.

Perhaps the above-mentioned @stringertheory has thoughts on this? Sorry for @-ing you, but your experience seems like a really good fit here.

**Comment by stringertheory** [comment]
Hey @harahu, no worries about @-ing, this is interesting, and I'm happy to learn about Awkward Arrays. They seem useful!

I agree with all the points in this thread:

- time-heterogeneous data is common in practice, especially with sensors and other event-driven systems
- [traces](https://github.com/datascopeanalytics/traces) is intended for time-heterogeneous data, but prioritizes ease of use on messy small-to-medium datasets over scalability (e.g. I find that I start getting impatient with it around ~10 million points or so on a laptop)
- also +1 to what @mloning mentions around needing to extend time series algorithms. Even the underlying [theory/methodology for time-heterogeneous data is lacking](http://www.eckner.com/papers/Algorithms%20for%20Unevenly%20Spaced%20Time%20Series.pdf) and/or very specialized according to specific use cases. For "basic" algorithms like a Fast Fourier Transform, time-heterogeneous data requires fundamental changes in the algorithms or a translation to even spacing, and there [are lots of ways to do it](https://scicomp.stackexchange.com/questions/593/how-do-i-take-the-fft-of-unevenly-spaced-data).

As you mention, whenever I need to use a more powerful toolset for time series analysis, I also end up making a (careful) translation to evenly-spaced data.

If anyone digs into this, it might be worth investigating the most efficient way of interpolating between time points in time-heterogenous data (maybe using or inspired by [scipy interpolation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html#scipy.interpolate.interp1d)?). That's ultimately what is needed in order to apply the toolset that's intended for evenly-spaced data. Traces uses [sortedcontainers](https://github.com/grantjenks/python-sortedcontainers) for that (sortedcontainers is a great library!), but maybe there are ways of interpolating between points in Awkward Arrays that would be more scalable.

**Comment by fkiraly** [comment]
@stringertheory, interesting! Didn't know about traces - would you have bandwidth for contribution?

An idea would be to pool efforts with awkward array, which under the hood could make traces - or "traces plus" - scalable?
And having a discussion around sktime data container interfaces?

**Comment by stringertheory** [comment]
@fkiraly I don't have enough time to contribute, but I'd be happy to talk some time!

**Comment by harahu** [comment]
> If anyone digs into this, it might be worth investigating the most efficient way of interpolating between time points in time-heterogenous data (maybe using or inspired by [scipy interpolation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html#scipy.interpolate.interp1d)?). That's ultimately what is needed in order to apply the toolset that's intended for evenly-spaced data.

I think this is a key point. One does not need to rework all algorithms if we just have efficient on-demand translation from time-heterogeneous  to homogeneous data. One part of that is different interpolation techniques. The other one is dealing with panel data of uneven length. Not sure what is the best solution there, knowing that [scikit-fda](https://github.com/GAA-UAM/scikit-fda) and similar tools use fixed grids across panel members.

**Comment by harahu** [comment]
Been thinking some more about this latter problem of unequal length panel members. I realize there are probably no "universal" way of comparing two such members, it is all case dependent. Depending on downstream use, you might want to translate to a fixed size representation by:

- Padding the smaller panel members to the size of the larger ones
- Truncating the larger ones to the size of the smaller ones
- Stretching or squeezing data to a uniform length (perhaps while adding an additional channel indicating the original time scale)

There are also some examples of situations where you might not want to do any translation at all, and just accept unequal size representations. If your model is recurrent (e.g. RNN), there isn't really a requirement for a fixed size representation.

**Comment by fkiraly** [comment]
@harahu, I think the optimal interface - beyond the "right data container" - supports two things:
* pipeline composition with transformers that convert different length into equal length and spacing
* pipeline composition with distances or kernels between different length or spaced sequences

**Comment by harahu** [comment]
> In the 2021 developer meeting, we settled on different data container conventions. Awkward-array is certainly something to consider later, but not for now.

I completely understand. The requirements discussed above are challenging to tackle in a general way. Is there any documentation for the new conventions you settled on?

**Comment by fkiraly** [comment]
Yes - currently with most detail in here:
https://github.com/alan-turing-institute/sktime/blob/main/examples/AA_datatypes_and_datasets.ipynb
(also in parts of the general documentation)
