### ISSUE TITLE
Prediction intervals for NaiveForecaster

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#480]
**Is your feature request related to a problem? Please describe.**
Currently, the [NaiveForecaster](https://github.com/alan-turing-institute/sktime/blob/master/sktime/forecasting/naive.py) doesn't support prediction intervals. 

**Describe the solution you'd like**
A clear description of prediction intervals for the naive strategies can be found [here](https://otexts.com/fpp3/prediction-intervals.html).

**Comment by gracewgao** [comment]
I'll give this a shot!

**Comment by John42506176Linux** [comment]
Hello, I'm currently a GSOC aspirant, and I was curious if @gracewgao was still working on this.

If it is possible, I'd love to try working on this too.

**Comment by fkiraly** [comment]
>I was curious if @gracewgao was still working on this.

The protocol here would be to wait for a week or two and assume "no" if there's no reaction.

**Comment by D3ViL-NK** [comment]
Hi @mloning,
I'm new to contributing, and I was paying attention to this issue for some time. I have a few questions in order to clarify that I'm on the right track.

- According to the description of prediction intervals,
![sigma hat](https://user-images.githubusercontent.com/43887812/110738921-bfd04480-81f5-11eb-9077-076b8a5b8179.JPG)
(In this equation)
   1. T must be the length of the training dataset, right?
   2. Is the number of parameters estimated in the forecasting method(K) is 1 for this issue?

- Other than that, everything is clear according to the [document](https://otexts.com/fpp3/prediction-intervals.html).
- I looked at the [NaiveForecaster](https://github.com/alan-turing-institute/sktime/blob/master/sktime/forecasting/naive.py), and I want to know that, what is the best way to return the prediction intervals,
   1. From a separate function inside the [NaiveForecaster](https://github.com/alan-turing-institute/sktime/blob/master/sktime/forecasting/naive.py)?
   2. Or from the **predict** function under [_sktime.py](https://github.com/alan-turing-institute/sktime/blob/15c5ccba8999ddfc52fe37fe4d6a7ff39a19ece3/sktime/forecasting/base/_sktime.py#L206)?
   3. Is there any other forecasting method in Sktime that the prediction interval already exists to use as an example?
   4. Or is there any other approach that you would like to suggest?

**Comment by gracewgao** [comment]
Hey, sorry I never got the chance to work on this - someone else is definitely welcome to take this on!

**Comment by mloning** [comment]
@D3ViL-NK sorry for the slow reply. 

* Prediction intervals are returned as part of the predict method as `predict(..., return_pred_int=True)`
* Regarding the computations, I'd your implementation against the the implementation in R and the examples in the FPP book

**Comment by D3ViL-NK** [comment]
@mloning, Thank you for the reply, 
I think I understand. I'll be implementing this, and I'll do a draft PR.

**Comment by thayeylolu** [comment]
I would like to implement the prediction intervals for the NaiveForcaster.
The approach I will be adopting is gotten from the FPP book.
<img width="817" alt="image" src="https://user-images.githubusercontent.com/13348874/113332395-06a6eb00-9319-11eb-80d5-39a4b9204185.png">

Since h is the number of steps ahead to predict. fh (the forecast horizon) = h. 
Each strategy (last, mean and drift) in the NaiveForcaster will be implemented accordingly.

**Comment by D3ViL-NK** [comment]
Please take a look at the Draft PR. I have some questions that are mentioned in the code (As comments).

**Comment by fkiraly** [comment]
@IlyasMoutawwakil covers most of this in #1865
