### ISSUE TITLE
ModuleNotFoundError: No module named 'sktime.transformers.panel'

### ISSUE THREAD

**Issue by adelphi207831197** [alan-turing-institute/sktime#481]
**Describe the bug**

I'm new to this. Please excuse me for asking a simple question.
I created a new Anaconda environment to test SKTime.
I ran the 'pip install sktime' to install SKTime, along with tsfresh and matplotlib to follow the examples.
When I try to follow the "Univariate time series classification with sktime" Time series forest example I get this error:

"ModuleNotFoundError: No module named 'sktime.transformers.panel'"

What other dependencies am I supposed to install?

**To Reproduce**

```python

from sktime.transformers.panel.summarize import RandomIntervalFeatureExtractor

```

**Expected behavior**

**Additional context**

python ex_univariateTSClassification1.py
Traceback (most recent call last):
  File "ex_univariateTSClassification1.py", line 22, in <module>
    from sktime.transformers.panel.summarize import RandomIntervalFeatureExtractor
ModuleNotFoundError: No module named 'sktime.transformers.panel'

**Versions**
SKTime version 0.4.3 was installed when I ran 'pip install sktime'
<details>

System:
    python: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\mee\AppData\Local\Continuum\anaconda3\envs\Python38-TimeSeries\python.exe
   machine: Windows-8.1-6.3.9600-SP0

Python dependencies:
          pip: 20.2.4
   setuptools: 49.6.0
      sklearn: 0.23.2
        numpy: 1.19.4
        scipy: 1.5.3
       Cython: 0.29.17
       pandas: 1.1.4
   matplotlib: 3.3.2
       joblib: 0.17.0
        numba: None
     pmdarima: 1.7.1
      tsfresh: 0.17.0

</details>

**Comment by mloning** [comment]
Hi @adelphi207831197, 

Thanks for raising the issue. 

When you `pip install sktime` you install the latest stable release, so to run the example notebooks locally you need to make sure to checkout the latest stable release version of the notebooks (rather than using the most up-to-date changes on master), run: `git checkout v0.4.3`

Alternatively, you can install the latest development version from master using `pip install -e .` from the root directory of sktime (find out more here: https://www.sktime.org/en/latest/contributing.html).

**Comment by adelphi207831197** [comment]
Ah, thank you very much! I'll follow the example from the v0.4.3.

**Comment by ugmurthy** [comment]
Thanks @mloning

**Comment by MaxHeuillet** [comment]
Hi, 

I updated the package and installed all the dependencies but I still have this error:
`ModuleNotFoundError: No module named 'sktime.transformers.panel'`

When I write: `from sktime.transformers.panel.compose import ColumnConcatenator`

How can I solve this ? 

Thanks

**Comment by mloning** [comment]
Hi @MaxHeuillet, as said, when you `pip install sktime` you install the latest stable release, so to run the example notebooks locally you need to make sure to checkout the latest stable release version of the notebooks too (rather than using the most up-to-date changes on master), so run: `git checkout v0.4.3`

Alternatively, you can install the latest development version from master using `pip install -e .` from the root directory of cloned sktime repository (find out more here: https://www.sktime.org/en/latest/contributing.html). 

Hope this helps!

**Comment by mloning** [comment]
This should now be fixed in the new release https://github.com/alan-turing-institute/sktime/releases/tag/v0.5.0
