### ISSUE TITLE
[BUG] Transformers and its subdirectories __init__.py files are blank

### ISSUE THREAD

**Issue by Zain-K** [alan-turing-institute/sktime#491]
**Describe the bug**

 Under Transformers and its subdirectories the __init__.py files are blank

**To Reproduce**

Run the following code.

```python
from sktime.transformers.base import _SeriesToSeriesTransformer
from sktime.transformers.panel.tsfresh import TSFreshFeatureExtractor
from sktime.transformers.panel.reduce import Tabularizer
```

**Expected behavior**

This causes "Module not found" errors in Jupyter Notebook.

**Additional context**

I checked on the github repository manually to confirm and the said files are blank. Please assist with resolving. Thank you.
**Versions**
<details>

System:
python: 3.7.2 (default, Dec 29 2018, 06:19:36)  [GCC 7.3.0]
executable: ~/anaconda3/bin/python
machine: Linux-4.15.0-54-generic-x86_64-with-debian-buster-sid

Python dependencies:
          pip: 19.0.3
   setuptools: 40.6.3
      sklearn: 0.23.2
        numpy: 1.19.4
        scipy: 1.2.1
       Cython: 0.29.2
       pandas: 1.1.4
   matplotlib: 3.3.3
       joblib: 0.17.0
        numba: 0.43.0
     pmdarima: 1.7.1
      tsfresh: 0.17.0

</details>

**Comment by mloning** [comment]
Hi @Zain-K thanks for raising the issue. I'm not sure though what you mean. The `__init__.py` are supposed to be empty here. Running the code you posted works fine for me. 

Could you add some more context what your setup is (OS, versions, environments, etc)?

**Comment by Zain-K** [comment]
Hi

OS is Ubuntu 18.04.2 LTS. I have updated the bug report with the system details.
When running example 2 in Jupyter Notebook I am getting errors which emanate from this error:
ModuleNotFoundError: No module named 'sktime.transformers.panel'
Thank you.

**Comment by mloning** [comment]
Hi @Zain-K, 

When you `pip install sktime` you install the latest stable release, so to run the example notebooks locally you need to make sure to checkout the latest stable release version of the notebooks (rather than using the most up-to-date changes on master), run: `git checkout v0.4.3`

Alternatively, you can install the latest development version from master using `pip install -e .` from the root directory of sktime (find out more here: https://www.sktime.org/en/latest/contributing.html).
