### ISSUE TITLE
Expanding Window Splitter

### ISSUE THREAD

**Issue by ngupta23** [alan-turing-institute/sktime#520]
**Is your feature request related to a problem? Please describe.**

The sliding window splitter already exists, but I would also like to request the expanding window splitter as described [here](https://eng.uber.com/forecasting-introduction/#:~:text=In%20the%20sliding%20window%20approach,here%20in%20black%2C%20for%20training.&text=On%20the%20other%20hand%2C%20the,of%20data%20to%20work%20with.).

**Describe the solution you'd like**
The image in the link above describes how the splits can be achieved.

**Describe alternatives you've considered**
Currently manually only using `CutoffSplitter`, but what if I want to use this in `ForecastingGridSearchCV`. Use of expanding window with `ForecastingGridSearchCV` is currently unavailable as far as I could tell.

**Comment by mloning** [comment]
Hi again :) 

I'm not sure what the purpose of the expanding window splitter is compared to the sliding window splitter as our forecasting models remember (some part of) the past data anyway - so technically they all have access to an expanding window but some may decided to only use part of that expanding window (hence a sliding window).

**Comment by ngupta23** [comment]
Hi @mloning , It is just a different method to perform the temporal cross validation. The advantage is that you use more of the data to make predictions as the folds progress so some prefer that over a sliding window which limits the data used in each fold to a smaller number. It can have an impact on the model's performance for case like exponential smoothing.

**Comment by mloning** [comment]
Hi, I know what the expanding window cross-validation is, but as I said, our forecasting models remember (some part of) the past data anyway - so technically they all have access to an expanding window but some may decided to only use the last part of that expanding window (e.g. the last window in the `NaiveForecaster`). Does that make sense to you? I'm sorry if I can't express this very clearly at the moment ...

**Comment by aiwalter** [comment]
I am just following this discussion and have some thoughts. I think the model can only learn from data that is has seen. When using a sliding window, old data is not shown to all models. So if there is an important patern in the old data that might appear in future again, a sliding window training can be a problem because you might select a model that has not seen this old data. 

This can be solved with using expanding window. The problem of an expanding window is however that most likely in empiricism, the models with the bigger training data will have the better performance ("the bigger the better"). So in expanding window there is always a bias to select a model that has seen more data. So both window splitter methods have pros and cons.

Anyway I think it would be good to have an `ExpandingWindowSplitter`, so people would just have more choice based on what they prefer?

**Comment by mloning** [comment]
I'll close this one in favour of #552 to keep discussion in one place
