### ISSUE TITLE
y_pred = forecaster.predict(fh)  is giving a nan value [BUG]

### ISSUE THREAD

**Issue by Conet1502** [alan-turing-institute/sktime#531]
I am trying to follow the example forecasting problem with a slightly different data set and I get to the ReducedRegressionForecaster section my forecast.fit is outputting a nan value. I have attached the data set and jupyter notebook.

Thanks for your help.

[Example (2).zip](https://github.com/alan-turing-institute/sktime/files/5668493/Example.2.zip)

```python
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
#regressor = SVR(kernel = 'rbf',gamma='scale') 
regressor = KNeighborsRegressor(n_neighbors=1)
forecaster = ReducedRegressionForecaster(regressor=regressor, window_length=12, strategy="recursive")
m = forecaster.fit(y_train)
y_pred = forecaster.predict(fh)
plot_series(y_train, y_test, y_pred, labels=["y_train", "y_test", "y_pred"]);
smape_loss(y_test, y_pred)
```

**Expected behavior**
Something other than nan from y_pred = forecaster.predict(fh) ( last block of code)

**Comment by mloning** [comment]
Hi @Conet1502 - thanks for raising this issue! `fh` isn't set anywhere, what value do you use for `fh`? How do you load the data from the csv?

**Comment by Conet1502** [comment]
Hi @mloning -Maybe the file didn't save completely but the seventh cell in the jyputer notebook should be. Are you able to download the attached csv and jypter notebook in Example(2).zip?

fh = ForecastingHorizon(y_test.index, is_relative=False)
fh

**Comment by mloning** [comment]
Hi @Conet1502, thanks for providing the additional info. 

The problem is that you mis-specify the frequency of your data. You specify `pd.PeriodIndex(series.index, freq="H", name="Period")` but the data is not regularly sampled hourly data. The data only has three observation per day at 9, 12 and 18 o'clock if I understand it correctly. 

We currently don't handle this kind of irregular index. If you want to ignore the different durations between the observations, the easiest is to use a simple `pd.RangeIndex(len(series))` (replacing `pd.PeriodIndex(series.index, freq="H", name="Period")` in your code). You may also be to specify a custom frequency in pandas. 

I believe we should raise an error in this case instead of simply returning `nan`, but it's not easy to catch these cases. 

Hope this helps! 

FYI Take a look at this [guide](https://guides.github.com/features/mastering-markdown/) to find out more about how to format comments on GitHub, that'll make it a lot easier to read for others.

**Comment by Conet1502** [comment]
@mloning  Thanks for looking into this.
