### ISSUE TITLE
Change update method

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#647]
**Is your feature request related to a problem? Please describe.**
https://github.com/sktime/enhancement-proposals/pull/8

**Describe the solution you'd like**
The `update` method should 
* change to `update_params=True` as default, 
* implement a complete re-fit in the base forecaster as a fall-back option if not overridden in concrete implementations, but raise a warning if fall-back option is used

**Comment by fkiraly** [comment]
... and retain current behaviour if `update_params=False`.

**Comment by pabworks** [comment]
To clarify on this @mloning, this is `update_params=True` by default for **all** forecasters?

**Comment by mloning** [comment]
Hi @pabworks, thanks for starting to work on this! Yes, it applies to all update related methods. I think that once we change that we also need to implement refitting as the fall-back option and adjust the unit tests accordingly. 

I think we should deprecate `update_predict` once `evaluate` works (it basically does the same), and rename `update_predict_single` to `update_predict`. Those changes may be a bit more complicated, I'm happy to help out if you get stuck!

**Comment by fkiraly** [comment]
Actually, I disagree to deprecate `update_predict` depending on cv, simply since there are method specific efficient rolling prediction strategies.

Having said that, I now also think `evaluate` should simply call `update_predict`.

**Comment by mloning** [comment]
@fkiraly I understand that there are more efficient algorithms for a single update-predict step. Can you point me to an example for more efficient algorithms for multiple iterations that depend on CV?

**Comment by mloning** [comment]
If there are only a few special cases, I'd prefer having separate classes for this (e.g. `ARIMACV`) and keeping the base forecaster as simple as possible. Having an `update_predict` method for a single update-predict step is, however, important I think as that may be used in deployment too.

**Comment by fkiraly** [comment]
>I understand that there are more efficient algorithms for a single update-predict step. Can you point me to an example for more efficient algorithms for multiple iterations that depend on CV?

First, let me say that I don't think this is the *only* criterion here, as you may be implying.

I do think two things are relevant for this decision:
* whether there exists a single example where the implementation is different
* whether a shorthand is useful to the user

Even if the first wouldn't be the case, I'd still think there is a strong case through the second, as it would be the only pathway to allow the user to create one-step walk-forward forecasts for a long period of time without having to write loops. This is a common enough use case to warrant a dedicated interface point in my opinion, even if it is "only" a shorthand.

Regarding the example, I assume you mean: is there an example where `update_predict` applied multiple times can be computed more efficiently or easily in bulk than when applying the same function the same amount of times instead.

I think the answer is yes, and the most important example is perhaps:
an estimator tuned with respect to some mean score on fixed-horizon walk-forward forecasts.

If you know in advance that you want to do walk-forward prediction with this estimator, you would make sure you retain mean walk-forward losses *for each candidate grid parameter*, which you then update with the "update sample mean" update, instead of re-computing each time.

(I can write this in math if not too clear what I mean, let me know if I should)

**Comment by fkiraly** [comment]
FYI, the "update sample mean update" is $X\leftarrow X + \frac{X_{N+1}-X}{N+1}$ if you add a new sample data point $X_{N+1}$.

**Comment by mloning** [comment]
> Even if the first wouldn't be the case, I'd still think there is a strong case through the second, as it would be the only pathway to allow the user to create one-step walk-forward forecasts for a long period of time without having to write loops. This is a common enough use case to warrant a dedicated interface point in my opinion, even if it is "only" a shorthand.

What's the use case here that's not covered by the `evaluate` function?

**Comment by fkiraly** [comment]
>What's the use case here that's not covered by the evaluate function?

Both cover the use case, but the process of getting walk-forward predictions via `evaluate` is much more byzantine - not attached to the object you would expect "does" it (producing prediction is "the forecaster's business) and hidden behind column name and non-default parameter. Most users would probably not see it and find the externality particularly strange.
