### ISSUE TITLE
Extend `ForecastingGridSearchCV` to different CV strategies

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#649]
**Is your feature request related to a problem? Please describe.**
https://github.com/sktime/enhancement-proposals/pull/8/, #622, #64

**Describe the solution you'd like**
Add support for different temporal cross-validation (CV) strategies, this requires to: 
* add kwarg to constructor (`__init__`) of `ForecastingGridSearchCV` to specify CV strategy with possible values being ("refit", "update"), with "refit" as default
* internally, implement different strategies in `fit` method, calling `update` or `fit` of the estimator to be tuned

**Comment by fkiraly** [comment]
I'll also write up the different implemented algorithms in pseudocode as a reference for clarity.

**Comment by GuzalBulatova** [comment]
Hi! Am I correct that this has been fixed by #739, [1dfce6b](https://github.com/alan-turing-institute/sktime/commit/1dfce6b41c2acdb576acfc04b09d11bf115c92d1#diff-1b57e46d309eecd63b23ed79a5c092f9ac21e1cc843fd14a4b143a1822507b8d)(_tune.py)?

I'm fairly new and trying to find an issue that hasn't been partially solved already. 
Could you please point out to something that can be tackled by someone with minimal background in sktime/sklearn?

Thank you!

**Comment by mloning** [comment]
Hi @GuzalBulatova, yes that's right, #739 closes this issue. 

For good first issues, please see my comment on Gitter!
