### ISSUE TITLE
Binder build fails

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#662]
Binder seems to fail at the moment (thanks to Ammo for raising this issue on Discord), seems like one of the dependencies installations goes wrong. 

Perhaps we should add Binder to our CI to check if it builds (see #196).

**Comment by mloning** [comment]
For running repo2docker as a GitHub action, see e.g. here: https://github.com/alan-turing-institute/bridge-data-environment/blob/master/.github/workflows/repo2docker.yml

**Comment by ddorf** [comment]
Encountered this just now. Somehow the `matrixprofile` (dependency of `tsfresh`) install prompts an attempt to install `numpy>=1.20.0`, which doesn't go with `python<3.7`.

![Screenshot from 2021-03-14 21-26-36](https://user-images.githubusercontent.com/28767641/111084798-244c1600-850c-11eb-8d45-bb949dccba28.png)

Quick hack to bring all but one "getting started"-binders back up could be to drop the last line of `.binder/requirements.txt:
```python
tsfresh>=0.17.0
```

Any other ideas? Happy to investigate more as my first issue if that would help!

**Comment by fkiraly** [comment]
Yes, this seems like a sensible quick fix.

Quick questions:
* in which binder is `tsfresh` being used? It could be replaced by any other popular feature extractor for demo purposes and removed as a dependency entirely.
* could this alternatively be fixed by downgrading the `tsfresh` version required?
