### ISSUE TITLE
Order of X and y arguments in fit methods

### ISSUE THREAD

**Issue by ngupta23** [alan-turing-institute/sktime#682]
**Is your feature request related to a problem? Please describe.**

Most of sklearn compatible `fit` methods are called using X, y order

```python
# sklearn and (most) sklearn compatible libraries such as imblearn - fit definition
def fit(Xt, yt, **fit_params):
    ...

# call
self._final_estimator.fit(Xt, yt, **fit_params)
```

If the `_final_estimator` is a sktime model, this causes an issue since the X and y arguments get reversed because sktime `fit` methods are called using y, X argument order (reverse of sklearn and sklearn compatible libraries).

```python
# sktime fit methods
def fit(self, y, X=None, fh=None, **fit_params)
```

**Describe the solution you'd like**
It would be great if sktime argument order could be made consistent with sklearn and other sklearn compatible libraries by reversing the order of y and X arguments in fit.

y could default to None and an internal check could be added in the base class to make sure that this to be present, else flag an error.

```python
# sktime fit methods (proposed)
def fit(self, X=None, y=None, fh=None, **fit_params):
    if y is None:
        raise ValueError("y value was not provided")
```

**Describe alternatives you've considered**
I can not think of any.

**Additional context**
Calling sktime models using `imblearn` pipeline which uses sklearn compatible calls [using X, y format](https://github.com/scikit-learn-contrib/imbalanced-learn/blob/4162d2d8ef127a81238ee72ebabac55642daee7c/imblearn/pipeline.py#L281). This causes issues since sktime expects y to be the first argument, so X and y get flipped internally.

**Comment by fkiraly** [comment]
Quick comment: this suggests a major API change!
Reversing `y` and `X` was a conscious API choice due to the differences between tabular learning tasks and forecasting.

Note that in forecasting, `X` is optional while `y` is not, whereas in `sklearn` tabular learning, `y` is optional (in unsupervised instances) while `X` is not!

The rule "optional arguments come last" implies the ordering already.
That is not superseded by "we could make `y` optional too", since it does not change the "moral story", i.e., the semantic optionality.

**Comment by fkiraly** [comment]
pining @mloning for the forecasting module

**Comment by fkiraly** [comment]
An alternative we discussed internally is whether in forecasting, the symbols `y` and `X` should be exchanged while leaving the semantic meaning intact, i.e., `y`/`Y` for exogenous variables and `X` for endogenous ones. We decided against that due to the common association of the symbol `y` with "target" and `X` with "side information" being stronger than the association of `X` with "core/non-optional data".

**Comment by ngupta23** [comment]
Hi @fkiraly, Thanks for the quick feedback. I understand this was a conscious choice, but making sktime compatible with sklearn and other sklearn compatible API calls would open up more functionality to be built around sktime.

**Comment by mloning** [comment]
scikit-learn's API is for cross-sectional learning, forecasting and other time series tasks are considerably different to cross-sectional learning. I think it makes sense to have a different interface for different tasks. sktime is still compatible with scikit-learn via the reduction interface. Why doesn't that work in the above example? What other functionality do you have in mind that doesn't work with the current interface?
