### ISSUE TITLE
Suggestions for forecasting models validation improvement

### ISSUE THREAD

**Issue by rjafarau** [alan-turing-institute/sktime#707]
Hi @mloning @fkiraly @aiwalter @ngupta23

Currently, I'm trying to migrate my codebase from `statsmodels` and `pmdarima` to `sktime`. There are some nuances that I have noticed:

1. There is absolutely no difference between using `SlidingWindowSplitter` and `ExpandingWindowSplitter` when pass them to `ForecastingGridSearchCV`. New data is appended to `self._y` and `self._X` according to the selected splitter strategy (https://github.com/alan-turing-institute/sktime/issues/552#issuecomment-748685565, https://github.com/alan-turing-institute/sktime/issues/520#issuecomment-737325145), but: 
    - Training folds are still the same for both splitters.
    - Training folds become larger and larger. It's OK for `ExpandingWindowSplitter`, but not for `SlidingWindowSplitter`. For `SlidingWindowSplitter`'s training folds should have the same length and move forward step by step and forget the earliest data points.

2. I believe that `initial_window` and `start_with_window` parameters can be avoided in splitter classes to make them easier to understand (https://github.com/alan-turing-institute/sktime/issues/521, https://github.com/alan-turing-institute/sktime/issues/518). For example, I suggest the following signatures:
    - `SlidingWindowSplitter(window_length, fh, step_length)`: fixed size training windows
    - `ExpandingWindowSplitter(initial_window_length, fh, step_length)`: expanding training windows

    As you can see I was inspired by `pmdarima.model_selection`'s classes `SlidingWindowForecastCV` and `RollingForecastCV`.

3. `ForecastingGridSearchCV` doesn't support a multi-step forecasting horizon (https://github.com/alan-turing-institute/sktime/issues/633).

4. Also, it's good to add `cross_val_score` function in `sktime.forecasting.model_selection` that returns scores for each train/test folds. I found @aiwalter's evaluate function very similar to what I mean (https://github.com/alan-turing-institute/sktime/pull/657).

5. The final suggestion is about update vs refit trade-off.
    - For sliding window setting when the training fold has a fixed length there is only one option - call refit.
    - For expanding window setting, from my point of view, the better approach is to use update functionality and refit as a fall-back option.

Please let me know if any of my suggestions sound interesting to you. Thank you!

**Comment by mloning** [comment]
Thanks for your issue @rjafarau - feedback and improvement suggestions are very welcome!

In case you haven't seen it, we've summarised some of the motivations behind our design choices [here](https://github.com/sktime/enhancement-proposals/blob/master/steps/01_forecasting_api/model-evaluation-tuning.md). 

1. This is work in progress, we need to implement the same mechanism we have for the `evaluate` function inside of `ForecastingGridSearchCV`.
2. See my answer to 5
3. That is also work in progress, supporting multi-step forecasting horizons adds some complication in terms of aggregating performance metrics.
4. `evaluate` is meant to be used instead of `cross_val_score` - we can reconsider naming, but we wanted to make a clear distinction between model selection and model evaluation, something which isn't clearly distinguished in scikit-learn for example.
5. As far as I can see, there are the following main strategies: 
* blocked cross-validation, random subsampling with some distance between training and test windows,
* sliding windows, re-fitting the model for each training window,
* sliding windows with an initial window, using the initial window for training and subsequent windows for updating,
* expanding windows, refitting the model for each training window.

That's why we have the initial window parameter. Your help is very welcome if you think about contributing!
