### ISSUE TITLE
[BUG] load_from_ucr_tsv_to_dataframe yields pd.Series whose indices start at 1

### ISSUE THREAD

**Issue by LoadingByte** [alan-turing-institute/sktime#74]
**Describe the bug**

When using `sktime.utils.load_data.load_from_ucr_tsv_to_dataframe` to load one of UCR's TSV files as a `DataFrame` whose cells contain `Series`, the indices of those `Series` start at 1, as opposed to 0, what one would expect.

This leads to problems when fitting the `sktime.classifiers.elastic_ensemble.ElasticEnsemble` on such a `DataFrame` since that estimator (as well as some utility components employed by the estimator) expect the `Series` indices to start at 0.

I have no idea why `sktime.utils.load_data.load_from_ucr_tsv_to_dataframe` creates 1-indexed `Series`. For now, I'm working around the problem by manually resetting the indices of all loaded `Series` after import.

I haven't checked whether other means of loading the data also behave this way.

**To Reproduce**

```python
from sktime.utils.load_data import load_from_ucr_tsv_to_dataframe
from sktime.classifiers.elastic_ensemble import ElasticEnsemble

X_train, y_train = load_from_ucr_tsv_to_dataframe("GunPoint_TRAIN.tsv")

# what follows is the workaround
#X_train = X_train.applymap(lambda series: series.reset_index(drop=True))

elastic_ensemble = ElasticEnsemble()
elastic_ensemble.fit(X_train, y_train)
```

**Expected behavior**

To reiterate, `load_from_ucr_tsv_to_dataframe` should yield a `DataFrame` containing `Series` whose indices always start at 0.

**Versions**

<details>
Linux-4.19.45-1-MANJARO-x86_64-with-arch-Manjaro-Linux

Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0]
NumPy 1.16.4
SciPy 1.2.1
sktime 0.2.0
</details>

**Comment by goastler** [comment]
Hello @LoadingByte 

I have looked into the issue and you are correct, the dataframe is loaded with indices beginning at 1. This is because the TSV file has class labels at the beginning of each row and in moving these the indices are shifted up by 1, due to [this line](https://github.com/alan-turing-institute/sktime/blob/3cd0064f7750844178b60d67422b083b5004131a/sktime/utils/load_data.py#L174). I am currently working on a fix.

**Comment by LoadingByte** [comment]
That's great to hear, thank you! :)

**Comment by jasonlines** [comment]
Hi @LoadingByte, Thanks for spotting this and sorry for the delay in the fix (exam marking hell for the last 2 weeks!). As George mentioned above, the issue was just because the index wasn't reset to 0 after removing the first element of each line for the Y. 

I've accepted George's PR and merged into dev. Hopefully this issue should be resolved on the dev branch now, and the fix will propagate to master soon too in our next release - we're currently working on a code sprint so will hold off on a new release for a week or two however
