### ISSUE TITLE
[BUG] expected dtype object, got 'numpy.dtype[float32]' when running minirocket notebook

### ISSUE THREAD

**Issue by turmeric-blend** [alan-turing-institute/sktime#764]
**Describe the bug**
I'm running this [notebook](https://github.com/alan-turing-institute/sktime/blob/main/examples/minirocket.ipynb) and ran into this error 

> expected dtype object, got 'numpy.dtype[float32]'

at `minirocket.fit(X_train)`

**To Reproduce**
run https://github.com/alan-turing-institute/sktime/blob/main/examples/minirocket.ipynb

**Expected behavior**
no error

**Versions**
```
python: 3.7.10
Python dependencies:
          pip: 21.0.1
   setuptools: 52.0.0.post20210125
      sklearn: 0.23.1
       sktime: 0.5.3
  statsmodels: 0.12.2
        numpy: 1.20.2
        scipy: 1.6.2
       Cython: None
       pandas: 1.2.3
   matplotlib: None
       joblib: 1.0.1
        numba: 0.50.1
     pmdarima: None
      tsfresh: None

```
</details>

**Comment by favour-nerrise** [comment]
@turmeric-blend This error is possibly due to an incompatibility between your `numpy` and `numba` versions. I suggest upgrading `numba` to the latest version, e.g. `python3 -m pip install numba==0.53.0`. This might require a manual update to `llmvite` as well by doing, `python3 -m pip install --ignore-installed llvmlite`

**Comment by turmeric-blend** [comment]
Your configuration worked! Thanks :)

**Comment by zershaw** [comment]
Thanks :) ！You saved me.
