### ISSUE TITLE
Univariate TSC classifiers 

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#92]
I'm removing the dim_to_use pattern, and replacing it with throwing an exception if a multivariate problem is passed. This is the agreed pattern unless a classifier can internally deal with multivariate problems. Syntactically, I'm doing it like this. 

![image](https://user-images.githubusercontent.com/9594042/60627807-2f6a1b80-9de7-11e9-971d-eff5fe9a9487.png)

does this seem reasonable? Ultimately, I would like to replace it with a checkCapabilities type pattern, but this will do for now. Asking this to make sure, as it will roll out across contrib

**Comment by mloning** [comment]
Yes, I agree, so by default, all estimators only accept 1-dimensional data, unless they have bespoke methods of dealing with multivariate data, otherwise multivariate data is handled by meta-estimators like `ColumnTransformer` or `ColumnEnsembleClassifier`.

Should we enforce the same for our time series related transformers (e.g. for interval segmentation, Fourier transforms, etc)? 

For consistency, I suggest to have a function in `sktime.utils.validation` which checks this. 

I think we agreed to support numpy arrays or pandas series inside the dataframe (i.e. inside each cell). But this is a more general check I guess and should maybe be handled by the data container but happy to add it to `check_ts_array` function.

**Comment by mloning** [comment]
Something like this should do for now:
```python
def check_X_univariate(X):
    """Helper function to check input univariate input data.

     Parameters
    ----------
    X : pandas DataFrame

    Returns
    -------
    None

    Raises
    ------
    ValueError
        If X has more than one column. 

    """
    if not isinstance(X, pd.DataFrame):
        raise ValueError(f"Input data must be pandas DataFrame, but found: {type(X)}")

    if X.shape[1] > 1:
        raise ValueError(f"Input data must be a univariate pandas DataFrame with a single column, "
                         f"but found: {X.shape[1]} columns")
```

**Comment by fkiraly** [comment]
In terms of design, I strongly disagree with making 1-dimensional series as a column type requirement a default. That's just like making tables of primitives a default!

Instead, I'd think it's a *trait* of an estimator/transformer etc whether it can deal with higher-dimensional data. This is similar to traits "can deal with NA within series", "can deal with non-equally spaced series", or "can deal with heterogeneous time stamps".

It would also be more consistent with the typing/reduction philosophy: note how "splitting a D-dimensional series column into D 1-dimensional series columns" is similar to the series-to-primitive type of transformers - it's an act of reduction.
Why is this reduction: you lose the information which columns came from the same multi-dimensional series originally! This information may be useful since you may want to apply different multi-variate transformers (e.g., multi-variate Fourier transform, or multi-dimensional shapelets) to different multi-variate series.

**Comment by fkiraly** [comment]
Of course a default transformer action can be splitting if you have a TSC/TSR algorithm that can only deal with univariate series.

**Comment by TonyBagnall** [comment]
I'm not sure I understand the distinction between a trait and a capability or what exactly you are strongly disagreeing with! However it is implemented, the default behaviour for estimators is either passed a numpy array or a panda, and unless the estimator has the capability to build multivariate models, it assumes the panda has the series in the first column. If the data is not in the required format, it throws an exception since it cannot deal with it. 

the original discussion was related to whether we can set the dimension to use within the classifier. We decided not to.

**Comment by mloning** [comment]
@fkiraly 
It's a default in the sense of what's currently implemented and what all methods will be able to deal with. 

> It would also be more consistent with the typing/reduction philosophy: note how "splitting a D-dimensional series column into D 1-dimensional series columns" is similar to the series-to-primitive type of transformers - it's an act of reduction.

Yes, but we probably do not want to implement this for every estimator/transformer but rather as a meta-estimator/compositor e.g. `ColumnTransformer`, `ColumnEnsemble` `ColumnConcatenator` (writing this I prefer `ColumnConcatenator` over `TimeSeriesConcatenator`).

Estimator-specific multivariate approaches (multivariate Fourier transform, segmenting in multidimensional space, etc) would be implemented in the specific estimators. 

We can add estimator traits to reflect these functionalities.   

@TonyBagnall 
> the default behaviour for estimators is either passed a numpy array or a panda

Features should always be a pandas DataFrame (not a numpy array)

**Comment by TonyBagnall** [comment]
@mloning if a classifier wants to be sklearn compliant in terms of input, surely that is its internal business? All our classifiers pull the single dimension out into nparrays anyway (because they cannot yet handle unequal length series). Remember we are meant to be agile :)

**Comment by fkiraly** [comment]
@mloning 

>It's a default in the sense of what's currently implemented and what all methods will be able to deal with, so perhaps it should not be a ValueError in my function above, but rather a NotImplementedError.

Agreed

> Yes, but we probably do not want to implement this for every estimator/transformer but rather as a meta-estimator/compositor e.g. ColumnTransformer, ColumnEnsemble, ColumnConcatenator (writing this I prefer ColumnConcatenator over TimeSeriesConcatenator).
> Estimator-specific multivariate approaches (multivariate Fourier transform, segmenting in multidimensional space, etc) would be implemented in the specific estimators.

Agreed

>We can add estimator traits to reflect these functionalities.

Makes sense.
If @ablaom were here, I'd say it should be part of the scityping, and he would disagree.

**Comment by mloning** [comment]
> @mloning if a classifier wants to be sklearn compliant in terms of input, surely that is its internal business? All our classifiers pull the single dimension out into nparrays anyway (because they cannot yet handle unequal length series). Remember we are meant to be agile :) If we dont they are too slow to be useful
They can do internally whatever the like, but X should be a pandas DataFrame, no? Or do you also want to treat columns of a numpy array as time points of one dimension, not sure? I think we should stick to the pandas DataFrame with series in cells.

**Comment by fkiraly** [comment]
>I think we should stick to the pandas DataFrame with series in cells.

Agreed (unless it turns out there are major performance drawbacks)

**Comment by mloning** [comment]
Well there are major performance drawbacks, that's why we pull them out internally and put them into 2d numpy arrays. One alternative is to restrict ourselves to regular equal length time series data, in that case we could simply use 3d numpy arrays (as done in tslearn I believe).

**Comment by TonyBagnall** [comment]
god no, not considering changing, I think we have our wires crossed, I'm not proposing changes, I'm just not enforcing type, given its python, so if someone were to pass it a numpy array, it would still build. I think my issue is answered. Once we have the decorator for pandas we can make the capability handling better
