### ISSUE TITLE
[ENH] VAR and VECM models

### ISSUE THREAD

**Issue by GitHunter0** [alan-turing-institute/sktime#929]
@fkiraly update: almost done, all that is missing is `predict_interval` for VECM.

---

@fkiraly's summary of the discussion:

We should interface VAR and VECM from `statsmodels`.

- [x] VAR #1083, #1491
- [x] VECM #1141, #2829

---

Have you considered porting `Vector Autoregressions (VAR)` and `Vector Error Correction Models (VECM)` from [statsmodels](https://www.statsmodels.org/dev/vector_ar.html#)? This would be a great addition. Thank you

**Comment by fkiraly** [comment]
we first need to consolidate the multivariate forecasting interface, see #919 and #228

**Comment by fkiraly** [comment]
but yes, important next step - join the dev days if interested #863

**Comment by GitHunter0** [comment]
I'm very glad to know, thank you for the feedback

**Comment by fkiraly** [comment]
As discussed in the latest mentoring meeting @thayeylolu will be working on this.

The interface will assume `pd.DataFrame` as input to `_fit`, and as return from `_predict`, no other types for the moment.

This means it should eventually be compatible irrespective of whichever of the two proposed designs #980 and #1074 we go with.

FYI, @mloning.

**Comment by fkiraly** [comment]
Other implementation notes

* we should start by writing a short user journey design
* the statsmodels adapter may be a good way to go, but needs investigating
* tests may also need looking at, e.g., multivariate input generation

**Comment by thayeylolu** [comment]
User Journey Design

```python
class VectorAutoRegression(_StatsModelsAdapter)
```
- The tag`univariate-only` is set to false
- Constructor's parameter `dates` as used by statsmodel's [var](https://www.statsmodels.org/dev/generated/statsmodels.tsa.vector_ar.var_model.VAR.html#statsmodels.tsa.vector_ar.var_model.VAR)
- expected input is `pd.DataFrame`

**Comment by fkiraly** [comment]
this is not a complete user journey design - this should include specification, and usage (e.g., fitting, forecasting) in key use cases.

I also don't think that data should ever be passed to a constructor - look at the forecasting extension template, constructor arguments are reserved to be hyper-parameters and components (if any)

**Comment by thayeylolu** [comment]
Hi @fkiraly , I have updated the User Journey

**Comment by fkiraly** [comment]
just confirming what I said verbally earlier, the user journey should probably look like this:
```params
model = VAR(**params)
model.fit(y=y, fh=fh, X=X)
model.predict(X_new)
```

where `model.predict(X_new)` returns a data frame at indices of `fh`, and both `y` and `X` are data frame

**Comment by GitHunter0** [comment]
Thanks @fkiraly , it is great to know!

**Comment by fkiraly** [comment]
VECM is still open, adding good first issue tag.

**Comment by AurumnPegasus** [comment]
Hey @fkiraly, If open I would like to take up VECM

**Comment by fkiraly** [comment]
Great, @AurumnPegasus, all yours!

**Comment by AurumnPegasus** [comment]
Hey @fkiraly ,
Had a doubt related to one of the variables used in VECM class of statsmodels:

```
exog_coint : ndarray (nobs_tot x neqs) or None.
Deterministic terms inside the cointegration relation.
```

This variables is used in `estimate_vecm_ml` function of statsmodel's VECM class, and is required for getting the desired result. Now, in the estimator template for forecaster, the `_fit` method only takes `x`, `y` and `fh`. Since the parameter does not seem to be model parameter, but more related to input data, I was wondering if I could add another parameter to the `_fit` method to represent `exog_coint` and what should the variable name be (I am not very sure what significance it has in statistics).

**Comment by fkiraly** [comment]
Hm, interesting question.

I think it must be passed in the `__init__`,  since it is not a regular argument of `fit` etc.

I would further modify it to allow:
* a scalar (float)
* an 1D ndarray of size nobs
* an 2D ndarray or pd.DataFrame of size (any, neqs)

The first two are cast to the (required_size, neqs).

The third is used as look-up, and is sub-set to the indices of `X` before passed to the `fit` function.
