### ISSUE TITLE
[DOC problem] docstrings of metrics are incorrect - input types

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#959]
There are some problems with the metrics docstrings in `_functions`:

* the claimed inputs are `pandas Series of shape (fh,) or (fh, n_outputs)` - but `pandas.Series` don't have a "shape". Multivariate series should be `pandas.DataFrame`.
* the examples are `np.array`, which is not mentioned as a potential input.

This should be fixed, and we may also want to ascertain that the metrics indeed work for all those input types.

Assigning @RNKuhns as he has recently worked on this and will know the code inside-out.

**Comment by RNKuhns** [comment]
@fkiraly good catch. The good news this is an easy fix. The docstrings are wrong in the scaled metrics (e.g. mean_absolute_scaled_error, etc), but look correct in the other functions (specify that input can be pd.Series, pd.DataFrame or NumPy array). 

Under the hood the input check is using scikit-learn's input check which works correctly with any of those input types.

**Comment by RNKuhns** [comment]
@fkiraly I'm adding the PR for this now. Took some time to get it so I could build docs locally to verify changes. 

I've included updates that correct the docstring issues you found, and in general improved docstring definitions/formatting. 

I've also made sure existing test cases cover pd.Series and np.array input. Note that adding tests for pd.DataFrame support will be a separate PR because, I should test the `multioutput` parameter as part of that. To do that, I need to calculate the expected metrics with different values of `multioutput`, which will take a bit longer for me to do.
